(()=>{
'use strict';
const ECO_KEY='gups_economic_v1';
const DEFAULT_TENDER='oj';
const q=(s,r=document)=>r.querySelector(s), qa=(s,r=document)=>[...r.querySelectorAll(s)];
const money=n=>'B/. '+Number(n||0).toLocaleString('es-PA',{minimumFractionDigits:2,maximumFractionDigits:2});
const round=n=>Math.round((Number(n||0)+Number.EPSILON)*100)/100;
const same=(a,b)=>Math.abs(round(a)-round(b))<0.01;
const safe=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function injectCss(){if(q('link[href*="licitaciones-v5.css"]'))return;const l=document.createElement('link');l.rel='stylesheet';l.href='licitaciones-v5.css?v=20260819-5';document.head.appendChild(l)}
injectCss();
function baseState(){return{activeTender:DEFAULT_TENDER,tenders:{oj:{quoteFile:'',formFile:'',quoteTax:7,formTax:7,formComplete:false,signatureChecked:false,finalChecked:false,items:[]}}}}
function load(){try{return Object.assign(baseState(),JSON.parse(localStorage.getItem(ECO_KEY)||'{}'))}catch{return baseState()}}
const ECO=load();
function ensureTender(id){ECO.tenders=ECO.tenders||{};if(!ECO.tenders[id])ECO.tenders[id]={quoteFile:'',formFile:'',quoteTax:7,formTax:7,formComplete:false,signatureChecked:false,finalChecked:false,items:[]};return ECO.tenders[id]}
function tenderMeta(id){try{if(typeof tenders!=='undefined'){const t=tenders.find(x=>x.id===id);if(t)return t}}catch{}return{id,name:id==='oj'?'Data Center OJ':'Licitación',code:'',entity:''}}
function save(){localStorage.setItem(ECO_KEY,JSON.stringify(ECO));syncEconomic().catch(()=>{})}
async function syncEconomic(){if(!window.__gupsSb)return;const id=ECO.activeTender, data=ensureTender(id), t=tenderMeta(id);try{await window.__gupsSb.from('licitacion_economic').upsert({tender_code:t.code||id,quote_file_name:data.quoteFile||null,form_file_name:data.formFile||null,quote_tax:Number(data.quoteTax||0),form_tax:Number(data.formTax||0),form_complete:!!data.formComplete,signature_checked:!!data.signatureChecked,final_checked:!!data.finalChecked,state:data,updated_at:new Date().toISOString()},{onConflict:'tender_code'})}catch(e){}}
function toastMsg(msg){if(typeof toast==='function')toast(msg);else alert(msg)}
function addMenuAndPage(){const menu=q('.menu'),content=q('.content');if(!menu||!content||q('[data-page="economica"]'))return;const b=document.createElement('button');b.className='nav';b.dataset.page='economica';b.innerHTML='<span class="ico">$</span>Propuesta Económica';const comp=qa('.nav').find(x=>x.dataset.page==='competencia');menu.insertBefore(b,comp||null);const sec=document.createElement('section');sec.className='page';sec.id='economica';sec.innerHTML=`<div class="hero"><div><h2>Propuesta Económica</h2><p>Compara la cotización interna de Grupo UPS con los valores colocados en el formulario económico del pliego. La sección solo queda lista cuando cantidades, precios, ITBMS y total coinciden.</p></div><div class="hero-actions"><select id="ecoTenderSelect" class="eco-select"></select><button class="btn soft" id="ecoAddLine">＋ Agregar línea</button></div></div><div id="ecoDetected"></div><div id="ecoApp" style="margin-top:16px"></div>`;content.appendChild(sec);
try{pageTitles.economica='Propuesta Económica'}catch{}
b.onclick=()=>{if(typeof go==='function')go('economica');else showPage('economica');renderEconomic()};
q('#ecoAddLine').onclick=()=>addLine();fillTenderSelect();}
function showPage(id){qa('.page').forEach(p=>p.classList.toggle('active',p.id===id));qa('.nav').forEach(n=>n.classList.toggle('active',n.dataset.page===id));const h=q('#pageTitle');if(h)h.textContent='Propuesta Económica'}
function fillTenderSelect(){const s=q('#ecoTenderSelect');if(!s)return;let list=[];try{if(typeof tenders!=='undefined')list=tenders}catch{}if(!list.length)list=[{id:'oj',name:'Data Center OJ',code:'SDO-LPI-002-2025'}];s.innerHTML=list.map(t=>`<option value="${safe(t.id)}">${safe(t.name)} · ${safe(t.code||'')}</option>`).join('');s.value=ECO.activeTender;s.onchange=()=>{ECO.activeTender=s.value;ensureTender(s.value);save();renderEconomic()}}
function detectedEconomicRequirement(){try{const shared=JSON.parse(localStorage.getItem('gups_licit_shared')||'{}');const req=shared?.lastAnalysis?.requirements||[];return req.filter(r=>/precio|econ[oó]mic|cotizaci[oó]n|lista de precios|itbms|oferta monetaria|formulario de propuesta/i.test((r.name||'')+' '+(r.raw||''))).slice(0,6)}catch{return[]}}
function addLine(){const d=ensureTender(ECO.activeTender);d.items.push({id:'e'+Date.now(),description:'',quoteQty:1,formQty:1,quoteUnit:0,formUnit:0});save();renderEconomic();}
function removeLine(id){const d=ensureTender(ECO.activeTender);d.items=d.items.filter(x=>x.id!==id);save();renderEconomic()}
function totals(d){const quoteSub=round(d.items.reduce((a,x)=>a+Number(x.quoteQty||0)*Number(x.quoteUnit||0),0));const formSub=round(d.items.reduce((a,x)=>a+Number(x.formQty||0)*Number(x.formUnit||0),0));const quoteTaxAmt=round(quoteSub*Number(d.quoteTax||0)/100);const formTaxAmt=round(formSub*Number(d.formTax||0)/100);const quoteTotal=round(quoteSub+quoteTaxAmt),formTotal=round(formSub+formTaxAmt);return{quoteSub,formSub,quoteTaxAmt,formTaxAmt,quoteTotal,formTotal,diff:round(formTotal-quoteTotal)}}
function validation(d){const t=totals(d);const lines=d.items.length>0&&d.items.every(x=>same(x.quoteQty,x.formQty)&&same(x.quoteUnit,x.formUnit));const taxes=same(d.quoteTax,d.formTax);const totalsMatch=same(t.quoteTotal,t.formTotal);const files=!!d.quoteFile&&!!d.formFile;const ready=files&&lines&&taxes&&totalsMatch&&d.formComplete&&d.signatureChecked&&d.finalChecked;return{...t,lines,taxes,totalsMatch,files,ready}}
function renderDetected(){const box=q('#ecoDetected');if(!box)return;const hits=detectedEconomicRequirement();box.innerHTML=hits.length?`<div class="eco-detected"><strong>✓ El análisis del pliego encontró referencias económicas.</strong><span>${hits.map(x=>`Pág. ${x.page}: ${safe((x.name||'').slice(0,110))}`).join(' · ')}</span></div>`:`<div class="eco-detected neutral"><strong>Propuesta económica vinculada al expediente.</strong><span>Si el pliego contiene un formulario de precios, verifica la página exacta y completa aquí los mismos valores de la cotización interna.</span></div>`}
function renderEconomic(){fillTenderSelect();renderDetected();const app=q('#ecoApp');if(!app)return;const d=ensureTender(ECO.activeTender),v=validation(d),t=tenderMeta(ECO.activeTender);app.innerHTML=`
<div class="eco-status ${v.ready?'ready':v.totalsMatch&&d.items.length?'review':'blocked'}"><div><strong>${v.ready?'✓ PROPUESTA ECONÓMICA LISTA':v.totalsMatch&&d.items.length?'Montos coinciden · falta completar validaciones':'⚠ PROPUESTA ECONÓMICA PENDIENTE'}</strong><span>${safe(t.name||'Licitación')} · ${safe(t.code||'')}</span></div><span class="status ${v.ready?'ok':v.totalsMatch&&d.items.length?'warn':'bad'}">${v.ready?'LISTA':v.totalsMatch&&d.items.length?'REVISAR':'NO LISTA'}</span></div>
<div class="eco-files"><label class="eco-file"><input type="file" id="ecoQuoteFile" accept="application/pdf,.xlsx,.xls,.doc,.docx"><span class="eco-file-icon">📎</span><div><strong>Cotización interna Grupo UPS</strong><small>${d.quoteFile?safe(d.quoteFile):'Adjuntar archivo de referencia'}</small></div><em>${d.quoteFile?'ADJUNTA':'PENDIENTE'}</em></label><label class="eco-file"><input type="file" id="ecoFormFile" accept="application/pdf,.xlsx,.xls,.doc,.docx"><span class="eco-file-icon">📄</span><div><strong>Formulario económico del pliego</strong><small>${d.formFile?safe(d.formFile):'Adjuntar formulario completado'}</small></div><em>${d.formFile?'ADJUNTO':'PENDIENTE'}</em></label></div>
<div class="panel eco-panel"><div class="panel-head"><div><h3>Comparación línea por línea</h3><p>La columna izquierda representa la cotización aprobada. La derecha representa lo que se colocará en el formulario del pliego.</p></div><button class="btn small soft" id="ecoAddLine2">＋ Línea</button></div><div class="eco-table-wrap"><table class="eco-table"><thead><tr><th>Descripción</th><th colspan="2">Cotización interna</th><th colspan="2">Formulario del pliego</th><th>Validación</th><th></th></tr><tr class="subhead"><th></th><th>Cant.</th><th>Precio unit.</th><th>Cant.</th><th>Precio unit.</th><th></th><th></th></tr></thead><tbody>${d.items.length?d.items.map((x,i)=>rowHtml(x,i)).join(''):`<tr><td colspan="7" class="eco-empty">Todavía no hay productos o servicios. Presiona <strong>+ Agregar línea</strong>.</td></tr>`}</tbody></table></div></div>
<div class="eco-bottom"><div class="panel"><div class="panel-head"><div><h3>ITBMS y totales</h3><p>El total del formulario debe quedar exactamente igual al total de la cotización.</p></div></div><div class="eco-tax-grid"><div><label>ITBMS cotización %</label><input class="eco-num" id="quoteTax" type="number" min="0" step="0.01" value="${d.quoteTax}"></div><div><label>ITBMS formulario %</label><input class="eco-num" id="formTax" type="number" min="0" step="0.01" value="${d.formTax}"></div></div><div class="eco-totals"><div><span>Subtotal cotización</span><b>${money(v.quoteSub)}</b></div><div><span>ITBMS cotización</span><b>${money(v.quoteTaxAmt)}</b></div><div class="grand"><span>Total cotización</span><b>${money(v.quoteTotal)}</b></div><div><span>Subtotal formulario</span><b>${money(v.formSub)}</b></div><div><span>ITBMS formulario</span><b>${money(v.formTaxAmt)}</b></div><div class="grand"><span>Total formulario</span><b>${money(v.formTotal)}</b></div></div><div class="eco-difference ${v.totalsMatch?'match':'mismatch'}"><strong>${v.totalsMatch?'✓ Los totales coinciden':'⚠ Diferencia detectada'}</strong><span>${v.totalsMatch?'El formulario económico coincide con la cotización interna.':`Diferencia: ${money(Math.abs(v.diff))}. Revisa cantidades, precios o ITBMS.`}</span></div></div>
<div class="panel"><div class="panel-head"><div><h3>Control económico final</h3><p>No se considera lista hasta completar estas verificaciones.</p></div></div><div class="eco-checks">${checkHtml('ecoFormComplete','Formulario económico completo',d.formComplete)}${checkHtml('ecoSignature','Firma verificada, si corresponde según el pliego',d.signatureChecked)}${checkHtml('ecoFinal','Revisión final de cantidades, precio e ITBMS',d.finalChecked)}</div><div class="eco-mini-status">${miniStatus('Archivos adjuntos',v.files)}${miniStatus('Cantidades y precios coinciden',v.lines)}${miniStatus('ITBMS coincide',v.taxes)}${miniStatus('Total general coincide',v.totalsMatch)}</div></div></div>`;
bindEconomic();}
function rowHtml(x,i){const qty=same(x.quoteQty,x.formQty),price=same(x.quoteUnit,x.formUnit);return `<tr data-row="${safe(x.id)}"><td><input class="eco-desc" data-f="description" value="${safe(x.description)}" placeholder="Producto o servicio ${i+1}"></td><td><input class="eco-num" data-f="quoteQty" type="number" min="0" step="1" value="${x.quoteQty}"></td><td><input class="eco-num" data-f="quoteUnit" type="number" min="0" step="0.01" value="${x.quoteUnit}"></td><td><input class="eco-num ${qty?'okinput':'badinput'}" data-f="formQty" type="number" min="0" step="1" value="${x.formQty}"></td><td><input class="eco-num ${price?'okinput':'badinput'}" data-f="formUnit" type="number" min="0" step="0.01" value="${x.formUnit}"></td><td><div class="eco-line-check ${qty&&price?'ok':'bad'}">${qty&&price?'✓ COINCIDE':'⚠ REVISAR'}</div><small>${qty?'Cant. ✓':'Cant. ≠'} · ${price?'Precio ✓':'Precio ≠'}</small></td><td><button class="eco-trash" data-remove="${safe(x.id)}" title="Eliminar">×</button></td></tr>`}
function checkHtml(id,label,checked){return `<label class="eco-check"><input type="checkbox" id="${id}" ${checked?'checked':''}><span>${label}</span></label>`}
function miniStatus(label,ok){return `<div class="eco-mini ${ok?'ok':'bad'}"><span>${ok?'✓':'!'}</span><b>${label}</b></div>`}
function bindEconomic(){const d=ensureTender(ECO.activeTender);q('#ecoAddLine2')?.addEventListener('click',addLine);q('#ecoQuoteFile')?.addEventListener('change',e=>{d.quoteFile=e.target.files[0]?.name||d.quoteFile;save();renderEconomic();toastMsg('Cotización interna vinculada')});q('#ecoFormFile')?.addEventListener('change',e=>{d.formFile=e.target.files[0]?.name||d.formFile;save();renderEconomic();toastMsg('Formulario económico vinculado')});q('#quoteTax')?.addEventListener('change',e=>{d.quoteTax=Number(e.target.value||0);save();renderEconomic()});q('#formTax')?.addEventListener('change',e=>{d.formTax=Number(e.target.value||0);save();renderEconomic()});q('#ecoFormComplete')?.addEventListener('change',e=>{d.formComplete=e.target.checked;save();renderEconomic()});q('#ecoSignature')?.addEventListener('change',e=>{d.signatureChecked=e.target.checked;save();renderEconomic()});q('#ecoFinal')?.addEventListener('change',e=>{d.finalChecked=e.target.checked;save();renderEconomic()});qa('[data-row]').forEach(tr=>{qa('input[data-f]',tr).forEach(inp=>inp.addEventListener('change',()=>{const item=d.items.find(x=>x.id===tr.dataset.row);if(!item)return;const f=inp.dataset.f;item[f]=f==='description'?inp.value:Number(inp.value||0);save();renderEconomic()}))});qa('[data-remove]').forEach(b=>b.onclick=()=>removeLine(b.dataset.remove))}
function economicReady(id){return validation(ensureTender(id)).ready}
function injectEconomicTab(id){const tabs=q('#expTabs');if(!tabs||q('[data-tab="expEconomic"]'))return;const btn=document.createElement('button');btn.className='tab';btn.dataset.tab='expEconomic';btn.textContent='Propuesta Económica';const comp=q('[data-tab="expComp"]',tabs);tabs.insertBefore(btn,comp||null);const p=document.createElement('div');p.className='tab-panel';p.id='expEconomic';const before=q('#expComp');before?.parentElement.insertBefore(p,before);const v=validation(ensureTender(id));p.innerHTML=`<div class="eco-exp-card ${v.ready?'ready':'blocked'}"><div><strong>${v.ready?'✓ Propuesta económica validada':'⚠ Propuesta económica pendiente'}</strong><span>${v.totalsMatch&&ensureTender(id).items.length?'Los totales coinciden. Revisa las validaciones restantes.':'Cotización y formulario todavía no están validados.'}</span></div><button class="btn small primary" id="openEconomicFromExp">Abrir Propuesta Económica</button></div>`;btn.onclick=()=>{qa('.tab',tabs).forEach(x=>x.classList.toggle('active',x===btn));qa('.tab-panel',tabs.parentElement).forEach(x=>x.classList.toggle('active',x===p))};q('#openEconomicFromExp',p).onclick=()=>{ECO.activeTender=id;save();if(typeof closeModal==='function')closeModal('expModal');if(typeof go==='function')go('economica');renderEconomic()}}
function wrapOpenTender(){const old=window.openTender;if(typeof old!=='function')return;window.openTender=function(id){old(id);setTimeout(()=>injectEconomicTab(id),30)}}
function enhancedFinalReview(id){let req=[];try{if(id==='oj'&&typeof requirements!=='undefined')req=requirements}catch{}const econ=economicReady(id);const checks=[['Documentos requeridos',req.length?req.every(r=>r.done):false],['No subsanables revisados',req.length?req.filter(r=>r.critical).every(r=>r.done):false],['Firmas completas',req.length?req.filter(r=>r.sign).every(r=>r.stage>=2):false],['Escaneos / subidas',req.length?req.every(r=>r.done||r.stage>=4):false],['Formato revisado',true],['Vigencias verificadas',true],['Propuesta económica',econ]];const ok=checks.every(x=>x[1]);const title=q('#genericTitle'),body=q('#genericBody');if(!title||!body)return;title.textContent='Revisión final del expediente';body.innerHTML=`<div class="review-grid">${checks.map(x=>`<div class="review-item ${x[1]?'pass':'fail'}"><div><strong>${x[0]}</strong><span>${x[1]?'Validación completada':x[0]==='Propuesta económica'?'Cotización, formulario, ITBMS o total requieren revisión':'Requiere atención antes de presentar'}</span></div><span class="status ${x[1]?'ok':'bad'}">${x[1]?'✓ OK':'PENDIENTE'}</span></div>`).join('')}</div><div class="${ok?'final-ready':'final-blocked'}" style="margin-top:12px">${ok?'✓ EXPEDIENTE LISTO PARA PRESENTAR':'⚠ El expediente todavía no debe marcarse como listo. Corrige los puntos pendientes, incluida la propuesta económica.'}</div>${!econ?'<div class="review-foot"><button class="btn primary" id="goEcoReview">Revisar propuesta económica</button></div>':''}`;if(typeof openModal==='function')openModal('genericModal');q('#goEcoReview')?.addEventListener('click',()=>{if(typeof closeModal==='function')closeModal('genericModal');ECO.activeTender=id;save();if(typeof go==='function')go('economica');renderEconomic()})}
function interceptFinalReview(){document.addEventListener('click',e=>{const b=e.target.closest('#finalReviewBtn');if(!b)return;e.preventDefault();e.stopImmediatePropagation();let id=ECO.activeTender;try{if(typeof state!=='undefined'&&state.activeTender)id=state.activeTender}catch{}enhancedFinalReview(id)},true)}
function addDashboardEconomicAlert(){const hero=q('#dashboard .hero');if(!hero||q('#ecoDashboardNotice'))return;const n=document.createElement('div');n.id='ecoDashboardNotice';n.className='eco-dashboard-notice';n.innerHTML='<span>💲</span><div><strong>Control económico activado</strong><small>La propuesta no podrá quedar lista si el formulario del pliego no coincide con la cotización.</small></div><button class="btn small soft">Revisar</button>';hero.insertAdjacentElement('afterend',n);q('button',n).onclick=()=>{ECO.activeTender='oj';if(typeof go==='function')go('economica');renderEconomic()}}
function boot(){addMenuAndPage();wrapOpenTender();interceptFinalReview();addDashboardEconomicAlert();renderEconomic()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(boot,80));else setTimeout(boot,80);
window.GUPSEconomic={render:renderEconomic,isReady:economicReady,state:ECO};
})();