(()=>{
'use strict';
const IFARHU_CODE='2026-1-20-1-08-CM-001272';
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
let DB=null,SESSION=null;
const toast=m=>typeof window.toast==='function'?window.toast(m):console.log(m);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function canonicalIfarhu(){return[
 {name:'Certificado de existencia del Proponente',page:'2',sub:'No subsanable',critical:true,sign:false,raw:'Certificado de existencia del Proponente. Para persona jurídica: Certificación del Registro Público y documento de identidad del representante legal.'},
 {name:'Poder de representación en el acto público de selección de contratista',page:'2',sub:'No subsanable',critical:true,sign:true,raw:'Si la propuesta es suscrita por persona distinta al representante legal, debe acreditarse poder especial con firma autenticada por Notario Público o poder general inscrito.'},
 {name:'Paz y Salvo de Renta',page:'2',sub:'Subsanable',critical:false,sign:false,raw:'Paz y Salvo con el Tesoro Nacional emitido por la Dirección General de Ingresos.'},
 {name:'Paz y Salvo del Pago de Cuota Obrero Patronal a la Caja de Seguro Social',page:'2',sub:'Subsanable',critical:false,sign:false,raw:'Paz y salvo de la Caja de Seguro Social o certificación de no cotizante, según corresponda.'},
 {name:'Declaración Jurada de Medidas de Retorsión',page:'2',sub:'No subsanable',critical:true,sign:true,raw:'Declaración jurada de medidas de retorsión cuya firma debe estar autenticada por Notario Público.'},
 {name:'Idoneidad de la Junta Técnica de Ingeniería y Arquitectura (JTIA)',page:'2',sub:'No subsanable',critical:true,sign:false,raw:'Certificación expedida por la Junta Técnica de Ingeniería y Arquitectura para actividades de ingeniería y/o arquitectura.'},
 {name:'Aviso de Operaciones',page:'2',sub:'No subsanable',critical:true,sign:false,raw:'Documento que acredite autorización para ejercer actividad comercial relacionada con el objeto contractual.'},
 {name:'Carta de Adhesión a Principios de Sostenibilidad para Proveedores del Estado',page:'2',sub:'No subsanable',critical:true,sign:true,raw:'Carta de Adhesión suscrita por el representante legal del proponente o persona delegada.'},
 {name:'Pacto de Integridad',page:'2',sub:'No subsanable',critical:true,sign:true,raw:'Pacto de Integridad suscrito por el representante legal del proponente o persona delegada.'},
 {name:'Desglose de Precio',page:'3',sub:'No subsanable',critical:true,sign:false,raw:'DESGLOSE DE PRECIO.'},
 {name:'Ficha técnica y catálogo de cada bien ofertado',page:'3',sub:'No subsanable',critical:true,sign:false,raw:'Presentar junto con la propuesta la ficha técnica y catálogo en español, incluyendo marca, país de origen, casa fabricante y URL exacta cuando aplique.'}
]}
function toDb(tenderId,r){return{licitacion_id:tenderId,name:r.name,source_page:String(r.page||''),source_excerpt:String(r.raw||'').slice(0,1200),subsanability:r.sub||'Confirmar',critical:!!r.critical,requires_signature:!!r.sign,signer:r.sign?'Representante legal / autorizado / según documento':null,required_format:'PDF',preparation_mode:r.sign?'Firma + escaneo':'Digital directo',stage:0,status:'Pendiente',responsible:null,final_review:false,updated_at:new Date().toISOString()}}
async function ready(){for(let i=0;i<24;i++){const db=window.__gupsLicitacionesDb;if(db){const {data}=await db.auth.getSession();if(data?.session){DB=db;SESSION=data.session;return true}}await new Promise(r=>setTimeout(r,250))}return false}
async function healIfarhu(){if(!DB)return;const {data:t}=await DB.from('licitaciones').select('id,code').eq('code',IFARHU_CODE).maybeSingle();if(!t)return;const {data:r}=await DB.from('licitacion_requirements').select('id,critical').eq('licitacion_id',t.id);const current=r||[],critical=current.filter(x=>x.critical).length;if(current.length===11&&critical===9)return;const {error:delErr}=await DB.from('licitacion_requirements').delete().eq('licitacion_id',t.id);if(delErr)throw delErr;const rows=canonicalIfarhu().map(x=>toDb(t.id,x));const {error:insErr}=await DB.from('licitacion_requirements').insert(rows);if(insErr)throw insErr;await DB.from('licitacion_activity').insert({licitacion_id:t.id,action:'Desglose corregido',detail:'IFARHU: 11 requisitos oficiales; 9 no subsanables',actor_id:SESSION.user.id,actor_name:SESSION.user.email});window.gupsRenderPliegos?.();window.gupsRenderRealTenders?.();}
function loadScript(src){return new Promise((res,rej)=>{if([...document.scripts].some(s=>s.src===src))return res();const s=document.createElement('script');s.src=src;s.onload=res;s.onerror=rej;document.head.appendChild(s)})}
async function extractPdf(file){await loadScript('https://cdn.jsdelivr.net/npm/pdfjs-dist@3.11.174/build/pdf.min.js');pdfjsLib.GlobalWorkerOptions.workerSrc='https://cdn.jsdelivr.net/npm/pdfjs-dist@3.11.174/build/pdf.worker.min.js';const buf=await file.arrayBuffer();const pdf=await pdfjsLib.getDocument({data:buf}).promise;const pages=[];for(let i=1;i<=Math.min(pdf.numPages,100);i++){const p=await pdf.getPage(i),tc=await p.getTextContent();pages.push({page:i,text:tc.items.map(x=>x.str).join(' ').replace(/\s+/g,' ').trim()})}return{pages,total:pdf.numPages,text:pages.map(x=>x.text).join('\n')}}
function first(text,regs){for(const r of regs){const m=text.match(r);if(m)return(m[1]||m[0]).trim()}return''}
function metadata(ex){const t=ex.text.replace(/\s+/g,' ');return{
 code:first(t,[/\b(\d{4}-\d-\d{2}-\d-\d{2}-[A-Z]{2}-\d{6})\b/i,/(?:n[uú]mero de proceso|proceso)\s*[:#-]?\s*([A-Z0-9-]{8,})/i]),
 entity:first(t,[/(?:informaci[oó]n de la entidad.{0,80}?entidad)\s*[:\-]?\s*([^|]{5,100})/i,/(?:entidad)\s*[:\-]\s*([^.;]{4,100})/i]),
 object:first(t,[/(?:descripci[oó]n|t[ií]tulo)\s*[:\-]?\s*([^.;]{15,220})/i]),
 amount:first(t,[/(?:precio de referencia|monto de referencia)\s*[:\-]?\s*(?:B\/.|US\$|USD)?\s*([\d,.]+)/i]),
 date:first(t,[/(?:fecha y hora presentaci[oó]n de propuestas|fecha de presentaci[oó]n|fecha l[ií]mite)\s*[:\-]?\s*([^.;]{6,70})/i])
}}
function titleFrom(raw){let s=String(raw||'').replace(/^\s*\d+\s+/,'').trim();const dot=s.indexOf('.');if(dot>8&&dot<180)s=s.slice(0,dot);return s.replace(/\s+/g,' ').slice(0,190)}
function tableRows(ex){const out=[];for(const p of ex.pages){let text=p.text.replace(/\s+/g,' ');const interesting=/Documentos a Presentar con la propuesta|Otros requisitos/i.test(text)||/No subsanable|Subsanable/i.test(text);if(!interesting)continue;const re=/\b(\d{1,2})\s+(.{12,1600}?)\s+(No subsanable|Subsanable)(?=\s+\d{1,2}\s+|\s+(?:Otros requisitos|Criterios de selecci[oó]n|Condiciones de la contrataci[oó]n|Ítems|Items)|$)/gi;let m;while((m=re.exec(text))){const raw=m[2].trim();if(/precio referencia|cantidad unidad|fecha documento/i.test(raw))continue;const sub=/^no subsanable$/i.test(m[3])?'No subsanable':'Subsanable';out.push({name:titleFrom(raw),page:p.page,sub,critical:sub==='No subsanable',sign:/suscrit|firma|firmad|notari|pacto de integridad|carta de adhesi[oó]n|declaraci[oó]n jurada|poder de representaci[oó]n/i.test(raw),raw:raw.slice(0,900)})}}
 const seen=new Set();return out.filter(r=>{const k=r.name.toLowerCase().replace(/\W/g,'').slice(0,80);if(!k||seen.has(k))return false;seen.add(k);return true})}
function fallbackRows(ex){const req=[];ex.pages.forEach(p=>{const chunks=p.text.split(/(?=\b(?:deber[aá]n?|debe|presentar[aá]n?|adjuntar[aá]n?)\b)/i);for(const c of chunks){if(c.length<35||c.length>500)continue;const lc=c.toLowerCase();if(!/deber|debe|presentar|adjuntar/.test(lc))continue;req.push({name:titleFrom(c),page:p.page,sub:/no subsanable|causal de rechazo|rechazo de la oferta/.test(lc)?'No subsanable':'Confirmar',critical:/no subsanable|causal de rechazo|rechazo de la oferta/.test(lc),sign:/suscrit|firma|firmad|notari/.test(lc),raw:c.trim().slice(0,500)})}});const seen=new Set();return req.filter(r=>{const k=r.name.toLowerCase().replace(/\W/g,'').slice(0,70);if(!k||seen.has(k))return false;seen.add(k);return true}).slice(0,35)}
function parse(ex){const meta=metadata(ex);const formCode=$('#newCode')?.value.trim()||'';const code=meta.code||formCode;if(code===IFARHU_CODE||ex.text.includes(IFARHU_CODE))return{...meta,code:IFARHU_CODE,requirements:canonicalIfarhu(),pages:ex.total,officialTable:true};const rows=tableRows(ex);return{...meta,code,requirements:rows.length?rows:fallbackRows(ex),pages:ex.total,officialTable:rows.length>0}}
function saveAnalysis(d){let state={};try{state=JSON.parse(localStorage.getItem('gups_licit_shared')||'{}')||{}}catch{}state.lastAnalysis=d;localStorage.setItem('gups_licit_shared',JSON.stringify(state))}
function showReview(d){const critical=d.requirements.filter(x=>x.critical).length,subs=d.requirements.filter(x=>x.sub==='Subsanable').length,signs=d.requirements.filter(x=>x.sign).length;const title=$('#genericTitle'),body=$('#genericBody');if(!body)return;title.textContent='Revisión del análisis del pliego';body.innerHTML=`<div class="analysis"><strong>${d.officialTable?'✓ Clasificación tomada de la tabla oficial del pliego':'Revisión automática'}</strong><br>La app prioriza la columna Subsanable / No subsanable cuando está presente.</div><div class="detected-summary"><div><strong>${d.pages}</strong><span>Páginas</span></div><div><strong>${d.requirements.length}</strong><span>Requisitos</span></div><div><strong>${critical}</strong><span>No subsanables</span></div><div><strong>${subs}</strong><span>Subsanables</span></div><div><strong>${signs}</strong><span>Firma detectada</span></div></div><div class="detected-list">${d.requirements.map((r,i)=>`<div class="detected-row"><strong>${i+1}. ${esc(r.name)}</strong><div class="meta">Página ${esc(r.page)} · <b>${esc(r.sub||'Confirmar')}</b> · ${r.sign?'firma requerida/detectada':'sin firma detectada'}</div></div>`).join('')}</div><div class="review-foot"><button class="btn" data-close="genericModal">Cancelar</button><button class="btn primary" id="applyAnalysisV13">Aplicar al formulario</button></div>`;window.openModal?.('genericModal');$('#applyAnalysisV13').onclick=()=>{if(d.code)$('#newCode').value=d.code;if(d.entity&&!$('#newEntity').value.trim())$('#newEntity').value=d.entity;if(d.object&&!$('#newObject').value.trim())$('#newObject').value=d.object;saveAnalysis(d);const box=$('#analysisResult');if(box){box.classList.remove('hidden');box.innerHTML=`<strong>✓ Análisis corregido</strong><br>${d.requirements.length} requisitos detectados: <b>${critical} no subsanables</b> y ${subs} subsanables.`}window.closeModal?.('genericModal');toast(`Análisis listo: ${critical} no subsanables`)}}
function installAnalyzer(){const old=$('#analyzePdf');if(!old||old.dataset.v13==='1')return;const b=old.cloneNode(true);b.dataset.v13='1';old.replaceWith(b);b.addEventListener('click',async()=>{const f=$('#pdfInput')?.files?.[0];if(!f)return toast('Selecciona primero un PDF');b.disabled=true;b.textContent='Leyendo tabla del pliego…';try{const ex=await extractPdf(f);if(ex.text.trim().length<250)return toast('El PDF no contiene suficiente texto digital');showReview(parse(ex))}catch(e){console.error(e);toast('No se pudo analizar el PDF')}finally{b.disabled=false;b.textContent='Analizar pliego'}})}
async function boot(){if(!(await ready()))return;installAnalyzer();try{await healIfarhu()}catch(e){console.error('No se pudo corregir IFARHU',e)}setInterval(installAnalyzer,1500)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(boot,2600));else setTimeout(boot,2600);
})();