(()=>{
'use strict';
const q=(s,r=document)=>r.querySelector(s),qa=(s,r=document)=>[...r.querySelectorAll(s)];
function injectCss(){if(q('link[href*="licitaciones-v6.css"]'))return;const l=document.createElement('link');l.rel='stylesheet';l.href='licitaciones-v6.css?v=20260820-7';document.head.appendChild(l)}
injectCss();
function parseClose(t){const m=String(t?.close||'').match(/(\d{2})\/(\d{2})\/(\d{4})/);if(!m)return null;return new Date(Number(m[3]),Number(m[2])-1,Number(m[1]),23,59,59)}
function upcomingTenders(){let list=[];try{list=typeof tenders!=='undefined'?tenders:[]}catch{}const now=new Date();now.setHours(0,0,0,0);const max=new Date(now);max.setDate(max.getDate()+7);return list.filter(t=>{const d=parseClose(t);return d&&d>=now&&d<=max&&!['En evaluación','Adjudicada','No adjudicada'].includes(t.status)}).sort((a,b)=>parseClose(a)-parseClose(b))}
function daysLeft(t){const d=parseClose(t);if(!d)return null;const now=new Date();now.setHours(0,0,0,0);return Math.max(0,Math.ceil((d-now)/86400000))}
function enhanceUpcoming(){const cards=qa('#licitaciones .tender-summary .stat-card');const card=cards.find(c=>/cierre pr[oó]ximo|licitaciones que cierran pronto/i.test(c.textContent));if(!card)return;const up=upcomingTenders();card.classList.add('close-stat-smart');card.innerHTML=`<div class="label">Licitaciones que cierran pronto</div><div class="value">${up.length}</div><div class="sub">Dentro de los próximos 7 días</div><div class="close-list">${up.slice(0,3).map(t=>`<div class="close-name">${t.name} · ${t.closeShort} · faltan ${daysLeft(t)} día${daysLeft(t)===1?'':'s'}</div>`).join('')||'<div class="close-name">No hay cierres en los próximos 7 días</div>'}</div>`}
function addCloseAlerts(){let list=[];try{list=typeof tenders!=='undefined'?tenders:[]}catch{}setTimeout(()=>qa('#tenderGrid .tender-card').forEach(c=>{const btn=c.querySelector('[onclick*="openTender"]');const m=btn?.getAttribute('onclick')?.match(/openTender\('([^']+)'\)/);const t=m&&list.find(x=>x.id===m[1]);if(!t)return;const d=daysLeft(t);c.querySelector('.close-alert')?.remove();if(d!==null&&d<=7&&d>=0){const a=document.createElement('div');a.className='close-alert';a.textContent=`⚠ Cierra en ${d} día${d===1?'':'s'} · ${t.closeShort}`;c.querySelector('.object')?.insertAdjacentElement('afterend',a)}}),60)}
function boot(){enhanceUpcoming();addCloseAlerts();document.querySelector('[data-page="licitaciones"]')?.addEventListener('click',()=>setTimeout(()=>{enhanceUpcoming();addCloseAlerts()},120),true)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(boot,500));else setTimeout(boot,500);
})();