(()=>{
'use strict';
const DB_URL='https://vkpzfyvszhmxwnpnznob.supabase.co';
const DB_KEY='sb_publishable_xPB87jZysR1CbD1y0D61dg_N34ibSUIZ';
const STORAGE_KEY='gups_licitaciones_prod_auth';
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
let db=null,session=null,rows=[],filter='Todas',rendering=false;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const toast2=m=>typeof window.toast==='function'?window.toast(m):console.log(m);
const fmt=n=>'B/. '+Number(n||0).toLocaleString('es-PA',{minimumFractionDigits:2,maximumFractionDigits:2});
function dateObj(v){const d=v?new Date(v):null;return d&&!Number.isNaN(d.getTime())?d:null}
function shortDate(v){const d=dateObj(v);return d?d.toLocaleDateString('es-PA',{day:'2-digit',month:'short'}).replace('.','').toUpperCase():'—'}
function longDate(v){const d=dateObj(v);return d?d.toLocaleString('es-PA',{day:'2-digit',month:'2-digit',year:'numeric',hour:'numeric',minute:'2-digit'}):'Sin fecha'}
function nameOf(r){return (r.name||r.object||r.code||'Licitación').slice(0,90)}
function addStyle(){if($('#prodLicStyles'))return;const s=document.createElement('style');s.id='prodLicStyles';s.textContent=`.prod-pill{cursor:pointer}.prod-pill.ok{background:#e9f8ef!important;color:#067647!important}.prod-pill.off{background:#fff4e5!important;color:#9a6700!important}.prod-layer{position:fixed;inset:0;background:rgba(7,20,39,.68);z-index:99999;display:grid;place-items:center;padding:20px}.prod-card{width:min(430px,100%);background:#fff;border-radius:20px;padding:24px;border:1px solid #dbe2ec;box-shadow:0 24px 80px rgba(0,0,0,.28)}.prod-card h3{margin:0;color:#073b80;font-size:22px}.prod-card p{color:#667085;font-size:12px;line-height:1.5}.prod-card label{display:block;font-size:10px;font-weight:800;color:#475467;margin:11px 0 5px}.prod-card input{width:100%;border:1px solid #dbe2ec;border-radius:10px;padding:11px}.prod-actions{display:flex;gap:8px;justify-content:flex-end;margin-top:14px}.prod-error{min-height:18px;color:#b42318;font-size:11px;margin-top:7px}.prod-empty{padding:28px;text-align:center;color:#667085}.prod-empty strong{display:block;color:#073b80;font-size:15px;margin-bottom:5px}`;document.head.appendChild(s)}
async function ensureLib(){if(window.supabase?.createClient)return;await new Promise((res,rej)=>{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2';s.onload=res;s.onerror=rej;document.head.appendChild(s)})}
function pill(){const host=$('#userChip')||$('.top-actions');if(!host)return null;let p=$('#prodLicPill');if(!p){p=document.createElement('span');p.id='prodLicPill';p.className='sync-pill prod-pill off';p.textContent='Licitaciones: conectar';p.onclick=()=>showLogin();host.appendChild(p)}return p}
function status(ok,text){const p=pill();if(!p)return;p.textContent=text;p.classList.toggle('ok',ok);p.classList.toggle('off',!ok)}
async function agendaEmail(){try{if(window.__gupsSb){const {data}=await window.__gupsSb.auth.getSession();return data?.session?.user?.email||''}}catch{}return''}
async function showLogin(msg=''){addStyle();if($('#prodLicLayer'))return;const email=await agendaEmail();const l=document.createElement('div');l.id='prodLicLayer';l.className='prod-layer';l.innerHTML=`<div class="prod-card"><h3>Conectar Licitaciones</h3><p>La Agenda seguirá usando su Supabase actual. Esta sesión es solo para guardar y consultar licitaciones en el proyecto nuevo.</p><label>Correo</label><input id="prodEmail" type="email" value="${esc(email)}"><label>Contraseña</label><input id="prodPass" type="password"><div id="prodErr" class="prod-error">${esc(msg)}</div><div class="prod-actions"><button class="btn" id="prodCancel">Ahora no</button><button class="btn primary" id="prodLogin">Conectar</button></div><p>Si el usuario todavía no existe en el proyecto nuevo, hay que crearlo primero en <strong>Authentication → Users</strong>.</p></div>`;document.body.appendChild(l);$('#prodCancel').onclick=()=>l.remove();$('#prodLogin').onclick=signIn}
async function signIn(){const e=$('#prodEmail')?.value.trim(),p=$('#prodPass')?.value||'',err=$('#prodErr'),b=$('#prodLogin');if(!e||!p){err.textContent='Completa correo y contraseña.';return}b.disabled=true;b.textContent='Conectando…';try{const {data,error}=await db.auth.signInWithPassword({email:e,password:p});if(error)throw error;const expected=await agendaEmail();if(expected&&data.session?.user?.email?.toLowerCase()!==expected.toLowerCase()){await db.auth.signOut();throw new Error('Usa el mismo correo con el que entraste a la Agenda.')}session=data.session;$('#prodLicLayer')?.remove();status(true,'Licitaciones: conectado');await load();toast2('Base de Licitaciones conectada')}catch(x){err.textContent=x?.message?.includes('Invalid login')?'Ese usuario aún no existe en el proyecto nuevo o la contraseña no coincide.':(x.message||'No se pudo conectar.')}finally{b.disabled=false;b.textContent='Conectar'}}
function fields(){const fs=$$('#nueva .field');const by=t=>fs.find(f=>($('label',f)?.textContent||'').toLowerCase().includes(t))?.querySelector('input,textarea,select');const amount=by('monto de referencia'),deadline=by('fecha límite');if(amount&&!amount.id)amount.id='newAmount';if(deadline&&!deadline.id)deadline.id='newDeadline';return{code:$('#newCode'),entity:$('#newEntity'),object:$('#newObject'),amount,deadline}}
function cleanDemoForm(){const f=fields();if(f.code?.value==='SDO-LPI-002-2025'&&f.entity?.value==='Órgano Judicial'){f.code.value='';f.entity.value='';f.object.value='';if(f.amount)f.amount.value='';if(f.deadline)f.deadline.value=''}}
async function save(){if(!session){showLogin('Conecta la base antes de guardar.');return}const f=fields(),code=f.code?.value.trim(),entity=f.entity?.value.trim(),object=f.object?.value.trim(),deadline=f.deadline?.value||'',raw=f.amount?.value.trim()||'';if(!code)return toast2('Completa el número del proceso');if(!entity)return toast2('Completa la entidad');if(!object)return toast2('Completa el objeto');if(!deadline)return toast2('Completa la fecha límite');const amount=raw?Number(raw.replace(/[^0-9.-]/g,'')):null;if(raw&&!Number.isFinite(amount))return toast2('Revisa el monto');const d=new Date(deadline);if(Number.isNaN(d.getTime()))return toast2('Revisa la fecha límite');const b=$('#saveTender');b.disabled=true;b.textContent='Guardando…';try{const payload={code,name:object.slice(0,90),entity,object,reference_amount:amount,deadline:d.toISOString(),status:'En preparación',progress:0,created_by:session.user.id,updated_at:new Date().toISOString()};const {data,error}=await db.from('licitaciones').upsert(payload,{onConflict:'code'}).select().single();if(error)throw error;await db.from('licitacion_activity').insert({licitacion_id:data.id,action:'Licitación guardada',detail:`${code} · ${entity}`,actor_id:session.user.id,actor_name:session.user.email});await load();toast2('Licitación guardada en Supabase');if(window.gupsNavigate)window.gupsNavigate('licitaciones');setTimeout(renderList,20)}catch(x){console.error(x);toast2('No se pudo guardar: '+(x.message||'error'))}finally{b.disabled=false;b.textContent='Guardar licitación'}}
function wireSave(){const b=$('#saveTender');if(!b||b.dataset.prod==='1')return;b.dataset.prod='1';b.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();save()},true)}
async function load(){const {data,error}=await db.from('licitaciones').select('*').order('deadline',{ascending:true});if(error)throw error;rows=data||[];renderDashboard();renderList()}
function renderDisconnected(){const d=$('#dashFocus');if(d)d.innerHTML='<div class="prod-empty"><strong>Base de Licitaciones sin conectar</strong>Conecta Supabase para ver los procesos reales.</div>';const g=$('#tenderGrid');if(g)g.innerHTML='<div class="panel prod-empty"><strong>Datos de demostración desactivados</strong>Conecta la base nueva para cargar las licitaciones reales.</div>';const p=$('#dashboard .priority-main');if(p)p.innerHTML='<div class="eyebrow">Producción</div><h3>Conecta la base de Licitaciones</h3><p>Los procesos de prueba ya no se usan en esta vista.</p><div class="mini-actions"><button class="btn small" id="prodConnect">Conectar Supabase</button></div>';$('#prodConnect')?.addEventListener('click',()=>showLogin())}
function renderDashboard(){if(!session)return renderDisconnected();const list=rows.map(r=>({...r,name:nameOf(r),close:longDate(r.deadline),short:shortDate(r.deadline)}));const d=$('#dashFocus');if(d)d.innerHTML=list.length?list.slice(0,6).map(r=>`<div class="focus-row"><div><h4>${esc(r.name)}</h4><p>${esc(r.entity||'—')} · ${esc(r.code)}</p></div><div><div class="progress-label"><span>${esc(r.status||'En preparación')}</span><strong>${Number(r.progress||0)}%</strong></div><div class="progress-track"><div class="progress-bar" style="width:${Number(r.progress||0)}%"></div></div></div><div class="focus-meta"><span class="status ok">Real</span><span class="chip">${esc(r.short)}</span><button class="btn small soft" onclick="openTender('${r.id}')">Abrir</button></div></div>`).join(''):'<div class="prod-empty"><strong>Aún no hay licitaciones</strong>Registra el primer proceso desde Nueva licitación.</div>';const p=$('#dashboard .priority-main'),n=Date.now(),next=list.find(r=>dateObj(r.deadline)?.getTime()>=n)||list[0];if(p)p.innerHTML=next?`<div class="eyebrow">Prioridad de hoy</div><h3>${esc(next.name)}</h3><p>${esc(next.entity||'—')} · ${esc(next.code)} · cierre ${esc(next.close)}</p><div class="mini-actions"><button class="btn small" onclick="openTender('${next.id}')">Abrir expediente</button><button class="btn small" data-go="licitaciones">Ver todas</button></div>`:'<div class="eyebrow">Prioridad de hoy</div><h3>Sin procesos activos</h3><p>Cuando guardes una licitación aparecerá aquí.</p>';const cards=$$('#dashboard .priority-card .big');cards.forEach(c=>c.textContent='0');const tl=$('#dashboard .timeline');if(tl)tl.innerHTML=list.slice(0,4).map(r=>`<div class="timeline-item"><strong>${esc(r.short)} · ${esc(r.code)}</strong><span>${esc(r.entity||'—')} · ${esc(r.close)}</span></div>`).join('')||'<div class="timeline-item"><strong>Sin hitos</strong><span>No hay fechas registradas.</span></div>'}
function renderList(){if(rendering)return;const g=$('#tenderGrid');if(!g)return;if(!session)return renderDisconnected();rendering=true;const q=($('#tenderSearch')?.value||'').toLowerCase();const list=rows.filter(r=>(filter==='Todas'||r.status===filter)&&(`${r.code} ${r.entity||''} ${r.name||''} ${r.object||''}`.toLowerCase().includes(q)));g.innerHTML=list.length?list.map(r=>`<article class="tender-card status-prep"><div class="tender-top"><div><h4>${esc(nameOf(r))}</h4><div class="entity">${esc(r.code)} · ${esc(r.entity||'—')}</div></div><span class="status warn">${esc((r.status||'En preparación').toUpperCase())}</span></div><p class="object">${esc(r.object||'')}</p><div class="tender-kpis"><div class="tender-kpi"><div class="k">Cierre</div><div class="v">${esc(shortDate(r.deadline))}</div></div><div class="tender-kpi"><div class="k">Monto</div><div class="v">${fmt(r.reference_amount)}</div></div><div class="tender-kpi"><div class="k">Avance</div><div class="v">${Number(r.progress||0)}%</div></div><div class="tender-kpi"><div class="k">Origen</div><div class="v">Real</div></div></div><div class="tender-foot"><span class="chip">${esc(longDate(r.deadline))}</span><button class="btn small primary" onclick="openTender('${r.id}')">Abrir expediente</button></div></article>`).join(''):'<div class="panel prod-empty"><strong>No hay licitaciones con este filtro</strong>Registra un proceso nuevo o cambia los filtros.</div>';setTimeout(()=>rendering=false,0)}
function openReal(id){const r=rows.find(x=>x.id===id);if(!r)return;$('#expTitle').textContent=nameOf(r);$('#expSub').textContent=`${r.code} · ${r.entity||'—'}`;$('#expSummary').innerHTML=`<div class="exec-info-grid"><div class="exec-info full"><div class="k">Objeto</div><div class="v">${esc(r.object||'')}</div></div><div class="exec-info"><div class="k">Estado</div><div class="v">${esc(r.status||'En preparación')}</div></div><div class="exec-info"><div class="k">Cierre</div><div class="v">${esc(longDate(r.deadline))}</div></div><div class="exec-info"><div class="k">Monto</div><div class="v">${fmt(r.reference_amount)}</div></div></div>`;$('#expReqs').innerHTML='<div class="note">Los requisitos reales se conectarán en el siguiente paso.</div>';$('#expDocs').innerHTML='<div class="note">Los documentos reales se conectarán en el siguiente paso.</div>';$('#expSigns').innerHTML='<div class="note">Las firmas reales se conectarán en el siguiente paso.</div>';$('#expComp').innerHTML='<div class="note">La competencia se registrará después del cierre.</div>';$('#expHistory').innerHTML='<div class="timeline"><div class="timeline-item"><strong>Licitación registrada</strong><span>Guardada en Supabase</span></div></div>';window.openModal?.('expModal')}
function wire(){wireSave();$('#tenderSearch')?.addEventListener('input',()=>setTimeout(renderList,0));$('#tenderFilters')?.addEventListener('click',e=>{const b=e.target.closest('.filter');if(!b)return;filter=b.dataset.filter||'Todas';setTimeout(renderList,0)});const g=$('#tenderGrid');if(g)new MutationObserver(()=>{if(session&&!rendering)setTimeout(renderList,0)}).observe(g,{childList:true})}
async function init(){addStyle();cleanDemoForm();wire();pill();try{await ensureLib();db=window.supabase.createClient(DB_URL,DB_KEY,{auth:{storageKey:STORAGE_KEY,persistSession:true,autoRefreshToken:true,detectSessionInUrl:false}});window.__gupsLicitacionesDb=db;const {data:{session:s}}=await db.auth.getSession();session=s;if(session){status(true,'Licitaciones: conectado');await load()}else{status(false,'Licitaciones: conectar');renderDisconnected()}window.openTender=openReal}catch(x){console.error(x);status(false,'Licitaciones: error');renderDisconnected()}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(init,1400));else setTimeout(init,1400);
})();