const state={currentPage:'dashboard',activeTender:'oj',opportunityFilter:'all',tenderFilter:'Todas',docFilter:'Todos',resultsStatus:'available',signatureTender:'oj'};
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const money=n=>'US$'+Number(n).toLocaleString('en-US',{maximumFractionDigits:0});
const pct=n=>Number(n).toFixed(2).replace(/\.00$/,'')+'%';
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.classList.remove('show'),2200)}
function go(page){state.currentPage=page;$$('.page').forEach(p=>p.classList.toggle('active',p.id===page));$$('.nav').forEach(n=>n.classList.toggle('active',n.dataset.page===page));document.getElementById('pageTitle').textContent=pageTitles[page]||'Gestor de Licitaciones';document.getElementById('sidebar').classList.remove('open');document.getElementById('overlay').classList.remove('show');window.scrollTo({top:0,behavior:'smooth'});if(page==='documentos')renderDocuments();if(page==='firmas')renderSignatureFolders();if(page==='licitaciones')renderTenders();if(page==='competencia')renderCompetition();if(page==='resumen')renderExecutive();}
const pageTitles={dashboard:'Dashboard',oportunidades:'Radar de Oportunidades',nueva:'Nueva licitación',licitaciones:'Licitaciones',documentos:'Documentos Empresa',firmas:'Firmas requeridas',competencia:'Competencia',resumen:'Resumen Ejecutivo'};
document.querySelectorAll('[data-page]').forEach(b=>b.addEventListener('click',()=>go(b.dataset.page)));document.querySelectorAll('[data-go]').forEach(b=>b.addEventListener('click',()=>go(b.dataset.go)));
document.getElementById('menuToggle').onclick=()=>{document.getElementById('sidebar').classList.toggle('open');document.getElementById('overlay').classList.toggle('show')};document.getElementById('overlay').onclick=()=>{document.getElementById('sidebar').classList.remove('open');document.getElementById('overlay').classList.remove('show')};
const tenders=[
 {id:'oj',code:'SDO-LPI-002-2025',name:'Data Center OJ',entity:'Órgano Judicial',object:'Expansión y Fortalecimiento de Infraestructura de Respaldo y Servidores del Data Center.',status:'En preparación',statusClass:'status-prep',progress:58,close:'30/07/2026 · 10:00 a. m.',closeShort:'30 JUL',amount:5075000,pendingDocs:5,pendingSigns:5,critical:2,life:1},
 {id:'utp',code:'UTP-LP-2026-014',name:'Licitación UTP',entity:'Universidad Tecnológica de Panamá',object:'Suministro e instalación de sistemas UPS para infraestructura tecnológica.',status:'En preparación',statusClass:'status-prep',progress:82,close:'22/08/2026 · 10:00 a. m.',closeShort:'22 AGO',amount:185000,pendingDocs:2,pendingSigns:3,critical:1,life:1},
 {id:'ups3',code:'LC-01181-2026',name:'UPS 3 kVA',entity:'Entidad pública',object:'Suministro de equipos UPS de respaldo de 3 kVA.',status:'Lista para presentar',statusClass:'status-ready',progress:100,close:'25/08/2026 · 11:00 a. m.',closeShort:'25 AGO',amount:78000,pendingDocs:0,pendingSigns:0,critical:0,life:2},
 {id:'mant',code:'2026-34-UPS',name:'Mantenimiento preventivo',entity:'Entidad pública',object:'Servicio de mantenimiento preventivo especializado para equipos UPS.',status:'En evaluación',statusClass:'status-eval',progress:100,close:'12/08/2026 · Cerrada',closeShort:'CERRADA',amount:96000,pendingDocs:0,pendingSigns:0,critical:0,life:5}
];
const requirements=[
 {id:'reg',name:'Certificado de Registro Público vigente',sub:'Confirmar',done:true,sign:false,signer:'No requiere',page:'47',format:'PDF',prep:'Digital directo',critical:false,stage:2,steps:['Disponible','Subido','Revisado']},
 {id:'ced',name:'Cédula o pasaporte del representante legal',sub:'Confirmar',done:true,sign:false,signer:'No requiere',page:'47',format:'PDF',prep:'Digital directo',critical:false,stage:2,steps:['Disponible','Subido','Revisado']},
 {id:'bank',name:'Carta(s) de referencias bancarias',sub:'Confirmar',done:false,sign:true,signer:'Banco autorizado',page:'47 y 57',format:'PDF',prep:'Firma + escaneo',critical:false,stage:2,steps:['Preparado','Impreso','Firmado','Escaneado','Subido','Revisado']},
 {id:'exp',name:'Experiencia: proyecto mínimo US$1.5M',sub:'Confirmar',done:true,sign:true,signer:'Según evidencia',page:'47 y 57',format:'PDF',prep:'Digital / según evidencia',critical:false,stage:5,steps:['Preparado','Impreso','Firmado','Escaneado','Subido','Revisado']},
 {id:'cvpm',name:'CV Administrador de Proyecto',sub:'Confirmar',done:false,sign:true,signer:'Profesional + oferente',page:'58 y 125',format:'PDF',prep:'Firma + escaneo',critical:false,stage:1,steps:['Preparado','Impreso','Firmado','Escaneado','Subido','Revisado']},
 {id:'cvt',name:'CV técnicos certificados',sub:'Confirmar',done:false,sign:true,signer:'Profesional + oferente',page:'58 y 125',format:'PDF',prep:'Firma + escaneo',critical:false,stage:1,steps:['Preparado','Impreso','Firmado','Escaneado','Subido','Revisado']},
 {id:'tier',name:'Certificación Tier II TCDD',sub:'Confirmar',done:true,sign:false,signer:'No requiere',page:'47 y 57',format:'PDF',prep:'Digital directo',critical:false,stage:2,steps:['Disponible','Subido','Revisado']},
 {id:'iso',name:'Certificación ISO 27001',sub:'Confirmar',done:true,sign:false,signer:'No requiere',page:'48 y 57',format:'PDF',prep:'Digital directo',critical:false,stage:2,steps:['Disponible','Subido','Revisado']},
 {id:'maint',name:'Declaración de Mantenimiento de la Oferta',sub:'No subsanable',done:false,sign:true,signer:'Persona autorizada',page:'73–76',format:'PDF',prep:'Firma + escaneo',critical:true,stage:1,steps:['Preparado','Impreso','Firmado','Escaneado','Subido','Revisado']},
 {id:'offer',name:'Carta de Oferta',sub:'Confirmar',done:true,sign:true,signer:'Representante legal / autorizado',page:'60–65',format:'PDF',prep:'Firma + escaneo',critical:false,stage:5,steps:['Preparado','Impreso','Firmado','Escaneado','Subido','Revisado']},
 {id:'mfg',name:'Autorización del Fabricante',sub:'Confirmar',done:false,sign:true,signer:'Representante autorizado del fabricante',page:'75–77',format:'PDF',prep:'Firma + escaneo',critical:false,stage:1,steps:['Preparado','Impreso','Firmado','Escaneado','Subido','Revisado']},
 {id:'prices',name:'Listas de Precios / Servicios Conexos',sub:'No subsanable',done:true,sign:true,signer:'Oferente autorizado',page:'68–72',format:'PDF',prep:'Firma + escaneo',critical:true,stage:5,steps:['Preparado','Impreso','Firmado','Escaneado','Subido','Revisado']}
];
const signatureSets={oj:requirements.filter(r=>r.sign),utp:[{id:'utp1',name:'Carta de propuesta UTP',signer:'Representante legal',page:'21',format:'PDF',prep:'Firma + escaneo',critical:true,stage:1,steps:['Preparado','Impreso','Firmado','Escaneado','Subido','Revisado']},{id:'utp2',name:'Declaración jurada',signer:'Representante legal',page:'24',format:'PDF',prep:'Firma + escaneo',critical:false,stage:2,steps:['Preparado','Impreso','Firmado','Escaneado','Subido','Revisado']},{id:'utp3',name:'Carta de fabricante',signer:'Fabricante autorizado',page:'31',format:'PDF',prep:'Firma + escaneo',critical:false,stage:5,steps:['Preparado','Impreso','Firmado','Escaneado','Subido','Revisado']},{id:'utp4',name:'Ficha técnica',signer:'No requiere',page:'36',format:'PDF',prep:'Digital directo',critical:false,stage:2,steps:['Disponible','Subido','Revisado']}],ups3:[{id:'u1',name:'Carta de Oferta',signer:'Representante legal',page:'18',format:'PDF',prep:'Firma + escaneo',critical:false,stage:5,steps:['Preparado','Impreso','Firmado','Escaneado','Subido','Revisado']}],mant:[{id:'m1',name:'Formulario de propuesta',signer:'Representante legal',page:'12',format:'PDF',prep:'Firma + escaneo',critical:false,stage:5,steps:['Preparado','Impreso','Firmado','Escaneado','Subido','Revisado']}]};
function renderDashboard(){document.getElementById('dashFocus').innerHTML=tenders.slice(0,3).map(t=>`<div class="focus-row"><div><h4>${t.name}</h4><p>${t.entity} · ${t.code}</p></div><div><div class="progress-label"><span>${t.status}</span><strong>${t.progress}%</strong></div><div class="progress-track"><div class="progress-bar" style="width:${t.progress}%"></div></div></div><div class="focus-meta"><span class="status ${t.critical?'bad':'ok'}">${t.critical?`⚠ ${t.critical} críticos`:'Sin críticos'}</span><span class="chip">${t.closeShort}</span><button class="btn small soft" onclick="openTender('${t.id}')">Abrir</button></div></div>`).join('');}
renderDashboard();
const opportunities=[{id:'op1',score:92,entity:'Universidad Tecnológica de Panamá',title:'Suministro e instalación de UPS para centro de datos',desc:'Sistemas de respaldo, instalación, puesta en marcha y soporte técnico.',amount:'B/. 185,000',close:'02/09/2026',tags:['UPS','Data Center','Instalación'],type:'Nueva licitación'},{id:'op2',score:86,entity:'Caja de Seguro Social',title:'Mantenimiento de sistemas de respaldo eléctrico',desc:'Mantenimiento preventivo y correctivo de UPS para infraestructura crítica.',amount:'B/. 96,000',close:'06/09/2026',tags:['Mantenimiento','UPS','Baterías'],type:'Nueva licitación'},{id:'op3',score:78,entity:'Autoridad Pública',title:'Adecuación de sala técnica y climatización de precisión',desc:'Aire de precisión, gabinetes y adecuaciones para sala tecnológica.',amount:'B/. 140,000',close:'10/09/2026',tags:['Climatización','Gabinetes','Sala técnica'],type:'Posible oportunidad'},{id:'op4',score:83,entity:'Entidad Estatal',title:'Consulta de mercado para infraestructura crítica 2027',desc:'Llamado preliminar para conocer soluciones de respaldo, climatización y soporte.',amount:'Por definir',close:'Consulta temprana',tags:['Consulta mercado','UPS','Climatización'],type:'Oportunidad temprana',early:true}];
function renderOpportunities(){document.getElementById('opportunityGrid').innerHTML=opportunities.map(o=>`<article class="opp-card ${o.early?'early':''}"><div class="score" style="--pct:${o.score}%"><strong>${o.score}%</strong></div><span class="status ${o.early?'violet':o.score>=85?'ok':'warn'}">${o.type}</span><h4>${o.title}</h4><div class="entity">${o.entity}</div><p class="desc">${o.desc}</p><div class="opp-meta"><div><span>Monto</span><strong>${o.amount}</strong></div><div><span>Fecha</span><strong>${o.close}</strong></div></div><div class="tag-row">${o.tags.map(t=>`<span class="chip">${t}</span>`).join('')}</div><div class="opp-actions"><button class="btn small primary" onclick="interestOpportunity('${o.id}')">Me interesa</button><button class="btn small soft" onclick="toast('Seguimiento activado para esta oportunidad')">Dar seguimiento</button><button class="btn small" onclick="dismissOpportunity('${o.id}')">Descartar</button></div></article>`).join('');}
renderOpportunities();
function interestOpportunity(id){const o=opportunities.find(x=>x.id===id);document.getElementById('newEntity').value=o.entity;document.getElementById('newObject').value=o.title;go('nueva');toast('Oportunidad cargada en Nueva licitación')}
function dismissOpportunity(id){const card=document.querySelector(`[onclick="dismissOpportunity('${id}')"]`).closest('.opp-card');card.style.opacity='.35';card.style.transform='scale(.98)';toast('Oportunidad descartada en esta demo')}
document.getElementById('refreshRadar').onclick=()=>{const btn=document.getElementById('refreshRadar');btn.disabled=true;btn.textContent='Actualizando…';setTimeout(()=>{btn.disabled=false;btn.textContent='↻ Actualizar radar';toast('Radar actualizado · demo sin conexión directa aún')},850)};
function renderTenders(){const q=(document.getElementById('tenderSearch')?.value||'').toLowerCase();const f=state.tenderFilter;const list=tenders.filter(t=>(f==='Todas'||t.status===f)&&(`${t.code} ${t.name} ${t.entity}`.toLowerCase().includes(q)));document.getElementById('tenderGrid').innerHTML=list.map(t=>`<article class="tender-card ${t.statusClass}"><div class="tender-top"><div><h4>${t.name}</h4><div class="entity">${t.code} · ${t.entity}</div></div><span class="status ${t.status.includes('Lista')?'ok':t.status.includes('evaluación')?'violet':'warn'}">${t.status.toUpperCase()}</span></div><p class="object">${t.object}</p><div class="tender-kpis"><div class="tender-kpi"><div class="k">Cierre</div><div class="v">${t.closeShort}</div></div><div class="tender-kpi"><div class="k">Pendientes</div><div class="v">${t.pendingDocs} docs</div></div><div class="tender-kpi"><div class="k">Firmas</div><div class="v">${t.pendingSigns}</div></div><div class="tender-kpi"><div class="k">No subs.</div><div class="v">${t.critical}</div></div></div><div class="tender-progress"><div class="progress-label"><span>Avance del expediente</span><strong>${t.progress}%</strong></div><div class="progress-track"><div class="progress-bar" style="width:${t.progress}%"></div></div></div><div class="tender-foot"><div class="lifecycle" title="Nueva → Preparación → Lista → Presentada → Resultados → Evaluación"><span class="life-dot done"></span><span class="life-dot ${t.life>=1?'done':''}"></span><span class="life-dot ${t.life===2?'current':t.life>2?'done':''}"></span><span class="life-dot ${t.life===3?'current':t.life>3?'done':''}"></span><span class="life-dot ${t.life===4?'current':t.life>4?'done':''}"></span><span class="life-dot ${t.life>=5?'current':''}"></span><span class="chip">${money(t.amount)}</span></div><button class="btn small primary" onclick="openTender('${t.id}')">Abrir expediente</button></div></article>`).join('')||'<div class="panel">No se encontraron licitaciones con estos filtros.</div>';}
document.getElementById('tenderSearch').addEventListener('input',renderTenders);document.querySelectorAll('#tenderFilters .filter').forEach(b=>b.onclick=()=>{state.tenderFilter=b.dataset.filter;document.querySelectorAll('#tenderFilters .filter').forEach(x=>x.classList.toggle('active',x===b));renderTenders()});renderTenders();
function openTender(id){const t=tenders.find(x=>x.id===id);state.activeTender=id;document.getElementById('expTitle').textContent=t.name;document.getElementById('expSub').textContent=`${t.code} · ${t.entity}`;document.getElementById('expSummary').innerHTML=`<div class="exec-info-grid"><div class="exec-info full"><div class="k">Objeto</div><div class="v">${t.object}</div></div><div class="exec-info"><div class="k">Estado</div><div class="v">${t.status}</div></div><div class="exec-info"><div class="k">Cierre</div><div class="v">${t.close}</div></div><div class="exec-info"><div class="k">Monto de referencia</div><div class="v">${money(t.amount)}</div></div><div class="exec-info"><div class="k">Avance</div><div class="v">${t.progress}%</div></div></div>`;document.getElementById('expReqs').innerHTML=id==='oj'?requirements.map(r=>`<div class="rank-row ${r.critical?'ours':''}"><div class="rank-top"><strong>${r.name}</strong><span class="status ${r.critical?'bad':r.done?'ok':'warn'}">${r.critical?'NO SUBSANABLE':r.done?'LISTO':'PENDIENTE'}</span></div><span class="meta">Formato: ${r.format} · ${r.prep} · Página ${r.page}</span></div>`).join(''):'<div class="note">Detalle demostrativo disponible para esta licitación.</div>';document.getElementById('expDocs').innerHTML='<div class="note">La biblioteca documental se vincula automáticamente con el expediente y conserva la versión utilizada al momento de presentar.</div>';document.getElementById('expSigns').innerHTML='<div class="note">Las firmas se gestionan por licitación en la sección Firmas y se sincronizan con el expediente.</div>';document.getElementById('expComp').innerHTML=id==='mant'?'<div class="note">Resultados disponibles. Abre Competencia para ver participantes y ofertas.</div>':'<div class="note">La competencia aparecerá después del cierre cuando existan resultados disponibles.</div>';document.getElementById('expHistory').innerHTML='<div class="timeline"><div class="timeline-item"><strong>Licitación creada</strong><span>Expediente registrado</span></div><div class="timeline-item"><strong>Documentos vinculados</strong><span>Biblioteca de empresa revisada</span></div><div class="timeline-item"><strong>Última actualización</strong><span>Checklist actualizado</span></div></div>';openModal('expModal')}
document.querySelectorAll('#expTabs .tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('#expTabs .tab').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('#expModal .tab-panel').forEach(p=>p.classList.toggle('active',p.id===b.dataset.tab))});
let companyDocs=[{id:'rp',name:'Certificado de Registro Público',category:'Legal',renewal:'Cada 3 meses',issued:'02/07/2026',expiry:'02/10/2026',days:44,responsible:'Administración',status:'Vigente',used:['UTP','Órgano Judicial'],versions:3},{id:'dgi',name:'Paz y Salvo DGI',category:'Fiscal',renewal:'Periódica',issued:'31/05/2026',expiry:'31/08/2026',days:12,responsible:'Administración',status:'Por vencer',used:['Órgano Judicial','UPS 3 kVA'],versions:4},{id:'css',name:'Paz y Salvo CSS',category:'CSS',renewal:'Periódica',issued:'20/07/2026',expiry:'20/10/2026',days:62,responsible:'Administración',status:'Vigente',used:['UTP'],versions:3},{id:'iso',name:'ISO 27001',category:'Certificación',renewal:'Anual',issued:'15/01/2026',expiry:'15/01/2027',days:149,responsible:'Ingeniería',status:'Vigente',used:['Órgano Judicial'],versions:2},{id:'aviso',name:'Aviso de Operación',category:'Legal',renewal:'Permanente',issued:'—',expiry:'—',days:9999,responsible:'Administración',status:'Vigente',used:['UTP','Órgano Judicial'],versions:1},{id:'vertiv',name:'Certificación / Carta de fabricante',category:'Fabricante',renewal:'Según fabricante',issued:'01/06/2026',expiry:'01/06/2027',days:286,responsible:'Ventas',status:'Vigente',used:['UPS 3 kVA'],versions:2}];
function docStatus(d){if(d.status==='Vencido'||d.days<0)return ['VENCIDO','bad'];if(d.days<=30)return ['POR VENCER','warn'];return ['VIGENTE','ok']}
function renderDocuments(){const q=(document.getElementById('docSearch')?.value||'').toLowerCase(),f=state.docFilter;const docs=companyDocs.filter(d=>(f==='Todos'||(f==='Vigentes'&&d.days>30)||(f==='Por vencer'&&d.days>=0&&d.days<=30)||(f==='Vencidos'&&d.days<0)||(f==='Renovables'&&d.renewal!=='Permanente')||(f==='Permanentes'&&d.renewal==='Permanente'))&&(`${d.name} ${d.category}`.toLowerCase().includes(q)));document.getElementById('docGrid').innerHTML=docs.map(d=>{const [txt,cls]=docStatus(d);return `<article class="doc-card"><div class="panel-head"><div><h4>${d.name}</h4><div class="category">${d.category}</div></div><span class="status ${cls}">${txt}</span></div><div class="doc-details"><div class="doc-detail"><span>Renovación</span><strong>${d.renewal}</strong></div><div class="doc-detail"><span>Emitido</span><strong>${d.issued}</strong></div><div class="doc-detail"><span>Vence</span><strong>${d.expiry}</strong></div><div class="doc-detail"><span>Responsable</span><strong>${d.responsible}</strong></div><div class="doc-detail"><span>Tiempo restante</span><strong>${d.days>1000?'Sin vencimiento':d.days+' días'}</strong></div></div><div class="doc-uses"><span>Utilizado actualmente en:</span><div>${d.used.map(u=>`<span class="chip">${u}</span>`).join('')||'<span class="chip">Sin uso activo</span>'}</div></div><div class="doc-foot"><span class="chip">${d.versions} versiones</span><div><button class="btn small" onclick="viewDocument('${d.id}')">Ver</button> <button class="btn small soft" onclick="updateDocument('${d.id}')">Actualizar</button> <button class="btn small" onclick="historyDocument('${d.id}')">Historial</button></div></div></article>`}).join('')||'<div class="panel">No hay documentos con este filtro.</div>'}
document.getElementById('docSearch').addEventListener('input',renderDocuments);document.querySelectorAll('#docFilters .filter').forEach(b=>b.onclick=()=>{state.docFilter=b.dataset.filter;document.querySelectorAll('#docFilters .filter').forEach(x=>x.classList.toggle('active',x===b));renderDocuments()});
function viewDocument(id){const d=companyDocs.find(x=>x.id===id);document.getElementById('genericTitle').textContent=d.name;document.getElementById('genericBody').innerHTML=`<div class="exec-info-grid"><div class="exec-info"><div class="k">Categoría</div><div class="v">${d.category}</div></div><div class="exec-info"><div class="k">Estado</div><div class="v">${docStatus(d)[0]}</div></div><div class="exec-info"><div class="k">Vencimiento</div><div class="v">${d.expiry}</div></div><div class="exec-info"><div class="k">Responsable</div><div class="v">${d.responsible}</div></div></div><div class="note" style="margin-top:12px">En la versión conectada aquí se abrirá el PDF vigente almacenado en Supabase Storage.</div>`;openModal('genericModal')}
function updateDocument(id){const d=companyDocs.find(x=>x.id===id);document.getElementById('docEditId').value=id;document.getElementById('docName').value=d.name;document.getElementById('docCategory').value=d.category;document.getElementById('docRenewal').value=d.renewal;document.getElementById('docExpiry').value=d.expiry==='—'?'':d.expiry.split('/').reverse().join('-');document.getElementById('docResponsible').value=d.responsible;openModal('docModal')}
function historyDocument(id){const d=companyDocs.find(x=>x.id===id);document.getElementById('genericTitle').textContent='Historial · '+d.name;document.getElementById('genericBody').innerHTML=`<div class="timeline"><div class="timeline-item"><strong>Versión vigente</strong><span>Emitida ${d.issued} · vence ${d.expiry}</span></div><div class="timeline-item"><strong>Versión anterior</strong><span>Archivada · se conserva para trazabilidad</span></div><div class="timeline-item"><strong>Versión inicial</strong><span>Archivada · vinculada a expedientes históricos</span></div></div>`;openModal('genericModal')}
document.getElementById('addDocument').onclick=()=>{document.getElementById('docEditId').value='';document.getElementById('docForm').reset();openModal('docModal')};document.getElementById('docForm').onsubmit=e=>{e.preventDefault();const id=document.getElementById('docEditId').value;if(id){const d=companyDocs.find(x=>x.id===id);d.name=document.getElementById('docName').value;d.category=document.getElementById('docCategory').value;d.renewal=document.getElementById('docRenewal').value;d.responsible=document.getElementById('docResponsible').value;d.expiry=document.getElementById('docExpiry').value?document.getElementById('docExpiry').value.split('-').reverse().join('/'):'—';d.versions++;toast('Nueva versión guardada en la demo')}else{companyDocs.push({id:'d'+Date.now(),name:document.getElementById('docName').value,category:document.getElementById('docCategory').value,renewal:document.getElementById('docRenewal').value,issued:'19/08/2026',expiry:document.getElementById('docExpiry').value?document.getElementById('docExpiry').value.split('-').reverse().join('/'):'—',days:90,responsible:document.getElementById('docResponsible').value,status:'Vigente',used:[],versions:1});toast('Documento agregado en la demo')}closeModal('docModal');renderDocuments()};renderDocuments();
function renderSignatureFolders(){const folderData=tenders.slice(0,4).map(t=>({t,set:signatureSets[t.id]||[]}));document.getElementById('signatureFolders').innerHTML=folderData.map(({t,set})=>{const pending=set.filter(r=>r.signer!=='No requiere'&&r.stage<2).length,scan=set.filter(r=>r.signer!=='No requiere'&&r.stage>=2&&r.stage<4).length,complete=set.filter(r=>r.stage>=r.steps.length-1).length;return `<button class="folder ${state.signatureTender===t.id?'active':''}" onclick="selectSignatureTender('${t.id}')"><div class="folder-icon">▰</div><h4>${t.name}</h4><p>${t.code} · ${t.entity}</p><div class="folder-stats"><span class="status ${pending?'bad':'ok'}">${pending?pending+' firmas pendientes':'Firmas completas'}</span>${scan?`<span class="status warn">${scan} por escanear/subir</span>`:''}<span class="chip">${complete}/${set.length} finalizados</span></div></button>`}).join('');renderSignatureDetail()}
function selectSignatureTender(id){state.signatureTender=id;renderSignatureFolders()}
function renderSignatureDetail(){const t=tenders.find(x=>x.id===state.signatureTender),set=signatureSets[state.signatureTender]||[];document.getElementById('signatureDetailTitle').textContent=t.name;document.getElementById('signatureDetailSub').textContent=`${t.code} · ${set.length} documentos con control de preparación`;document.getElementById('signatureList').innerHTML=set.map(r=>`<div class="sign-row ${r.critical?'critical':''}"><div><h5>${r.name}</h5><p>Debe firmar: ${r.signer} · Página ${r.page}</p><div class="prep-line"><span class="status ${r.prep.includes('Firma')?'warn':'blue'}">${r.prep.includes('Firma')?'🖨 Firma + escaneo':'📎 Digital directo'}</span><span class="chip">Formato: ${r.format}</span>${r.critical?'<span class="status bad">⚠ NO SUBSANABLE</span>':''}</div></div><div class="steps">${r.steps.map((s,i)=>`<div class="step ${i<r.stage?'done':i===r.stage?'current':''}"><span class="dot">${i<r.stage?'✓':i+1}</span>${s}</div>`).join('')}</div><div class="sign-actions"><button class="btn small" onclick="toast('Abrir referencia del pliego · demo')">Ir al pliego</button>${r.stage<r.steps.length?`<button class="btn small primary" onclick="advanceSignature('${state.signatureTender}','${r.id}')">${r.stage>=r.steps.length-1?'Finalizar':'Avanzar etapa'}</button>`:'<span class="status ok">FINALIZADO</span>'}</div></div>`).join('')||'<div class="note">No hay documentos de firma para esta licitación.</div>'}
function advanceSignature(tid,rid){const r=(signatureSets[tid]||[]).find(x=>x.id===rid);if(!r)return;r.stage=Math.min(r.stage+1,r.steps.length);if(tid==='oj'){const base=requirements.find(x=>x.id===rid);if(base){base.stage=r.stage;base.done=r.stage>=r.steps.length}}renderSignatureFolders();toast(r.stage>=r.steps.length?'Documento finalizado y sincronizado':'Etapa actualizada')}
renderSignatureFolders();
const competitors=[{name:'Empresa Gamma',amount:4650000,ours:false},{name:'Grupo UPS, S.A.',amount:4720000,ours:true},{name:'Empresa Alpha',amount:4890000,ours:false},{name:'Empresa Beta',amount:5010000,ours:false}];
const our=competitors.find(x=>x.ours),lowest=Math.min(...competitors.map(x=>x.amount)),difference=our.amount-lowest,diffPct=difference/lowest*100,rank=[...competitors].sort((a,b)=>a.amount-b.amount).findIndex(x=>x.ours)+1,probability=74;
function renderCompetition(){document.getElementById('compStatusLabel').textContent=state.resultsStatus==='available'?'Resultados disponibles':'Esperando resultados';document.getElementById('compStatusLabel').className='status '+(state.resultsStatus==='available'?'ok':'warn');document.getElementById('ourOffer').textContent=money(our.amount);document.getElementById('lowestOffer').textContent=money(lowest);document.getElementById('difference').textContent=money(difference);document.getElementById('differencePct').textContent=pct(diffPct);document.getElementById('ourPosition').textContent=`${rank} de ${competitors.length}`;document.getElementById('participants').textContent=competitors.length;const max=Math.max(...competitors.map(x=>x.amount));document.getElementById('ranking').innerHTML=[...competitors].sort((a,b)=>a.amount-b.amount).map((c,i)=>`<div class="rank-row ${c.ours?'ours':''}"><div class="rank-top"><div><strong>${i+1}. ${c.name}</strong><span class="meta">${c.ours?'Nuestra oferta':'Oferta detectada'}</span></div><span class="amount">${money(c.amount)}</span></div><div class="rank-bar-track"><div class="rank-bar" style="width:${(c.amount/max*100).toFixed(1)}%"></div></div></div>`).join('');document.getElementById('probability').textContent=probability+'%';document.getElementById('probLabel').textContent=probability>=75?'ALTA':probability>=55?'MEDIA':'BAJA';document.getElementById('probRing').style.background=`conic-gradient(var(--ok) 0 ${probability}%,#e7ebf0 ${probability}% 100%)`;document.getElementById('compReading').innerHTML=`<strong>Lectura ejecutiva:</strong> Grupo UPS presentó la <strong>${rank===1?'oferta más baja':rank+'ª oferta por precio'}</strong>. Nuestra propuesta está <strong>${money(difference)}</strong> (${pct(diffPct)}) por encima de la oferta más baja registrada. El resultado final depende también del cumplimiento documental, técnico y de la evaluación oficial.`;}
document.getElementById('refreshResults').onclick=()=>{state.resultsStatus='waiting';renderCompetition();const b=document.getElementById('refreshResults');b.disabled=true;b.textContent='Consultando…';setTimeout(()=>{state.resultsStatus='available';renderCompetition();b.disabled=false;b.textContent='↻ Actualizar resultados';toast('Resultados actualizados · datos demostrativos')},900)};renderCompetition();
function renderExecutive(){document.getElementById('execProcess').textContent='SDO-LPI-002-2025';document.getElementById('execEntity').textContent='Órgano Judicial';document.getElementById('execObject').textContent='Expansión y Fortalecimiento de Infraestructura de Respaldo y Servidores del Data Center.';document.getElementById('execOur').textContent=money(our.amount);document.getElementById('execLow').textContent=money(lowest);document.getElementById('execDiff').textContent=`${money(difference)} · ${pct(diffPct)}`;document.getElementById('execRank').textContent=`${rank} de ${competitors.length}`;document.getElementById('execParticipants').textContent=competitors.length;document.getElementById('execProb').textContent=probability+'%';document.getElementById('execProbRing').style.background=`conic-gradient(var(--ok) 0 ${probability}%,#e7ebf0 ${probability}% 100%)`;document.getElementById('execOffers').innerHTML=[...competitors].sort((a,b)=>a.amount-b.amount).map((c,i)=>`<div class="rank-row ${c.ours?'ours':''}"><div class="rank-top"><div><strong>${i+1}. ${c.name}</strong><span class="meta">${c.ours?'Nuestra oferta':'Oferente participante'}</span></div><span class="amount">${money(c.amount)}</span></div></div>`).join('');document.getElementById('execReading').innerHTML=`Grupo UPS quedó en la <strong>posición ${rank} de ${competitors.length}</strong> por monto ofertado. Nuestra propuesta se ubicó <strong>${pct(diffPct)}</strong> por encima de la oferta más baja. El índice competitivo estimado es de <strong>${probability}%</strong>; es un indicador interno y no representa garantía de adjudicación.`}
document.getElementById('printExec').onclick=()=>window.print();document.getElementById('copyExec').onclick=async()=>{try{await navigator.clipboard.writeText(location.href.split('#')[0]+'#resumen');toast('Enlace del resumen copiado')}catch{toast('No se pudo copiar automáticamente')}};document.getElementById('shareExec').onclick=async()=>{const data={title:'Resumen Ejecutivo · Licitación',text:'Resumen de participación y competencia · Grupo UPS',url:location.href.split('#')[0]+'#resumen'};if(navigator.share){try{await navigator.share(data)}catch{}}else{document.getElementById('copyExec').click()}};renderExecutive();
document.getElementById('pdfInput').onchange=()=>{const f=document.getElementById('pdfInput').files[0];document.getElementById('pdfName').textContent=f?f.name:'Ningún archivo seleccionado'};
document.getElementById('analyzePdf').onclick=()=>{const f=document.getElementById('pdfInput').files[0];if(!f){toast('Selecciona primero un PDF');return}document.getElementById('analysisResult').classList.remove('hidden');document.getElementById('analysisResult').innerHTML=`<strong>✓ Análisis demostrativo completado</strong><br>El prototipo detectó estructura documental, firmas, formatos y fechas. La lectura automática real del PDF se conectará al backend.<div class="analysis-grid"><div class="analysis-chip"><strong>12</strong><span>Requisitos</span></div><div class="analysis-chip"><strong>2</strong><span>No subsanables</span></div><div class="analysis-chip"><strong>5</strong><span>Requieren firma</span></div><div class="analysis-chip"><strong>7</strong><span>Digital directo</span></div><div class="analysis-chip"><strong>5</strong><span>Firma + escaneo</span></div></div>`;toast('Pliego analizado en modo demostración')};document.getElementById('saveTender').onclick=()=>toast('Licitación guardada en esta demo');
function openModal(id){document.getElementById(id).classList.add('open')}function closeModal(id){document.getElementById(id).classList.remove('open')}window.openModal=openModal;window.closeModal=closeModal;window.openTender=openTender;window.interestOpportunity=interestOpportunity;window.dismissOpportunity=dismissOpportunity;window.viewDocument=viewDocument;window.updateDocument=updateDocument;window.historyDocument=historyDocument;window.selectSignatureTender=selectSignatureTender;window.advanceSignature=advanceSignature;window.toast=toast;
document.querySelectorAll('.modal').forEach(m=>m.addEventListener('click',e=>{if(e.target===m)m.classList.remove('open')}));document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>closeModal(b.dataset.close));
if(location.hash==='#resumen')go('resumen');