(()=>{
'use strict';
const BUCKET='LICITACIONES GUPS';
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
let DB=null,SESSION=null,TENDERS=[],REQS=[],FILES=[],activePliego=null;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>'B/. '+Number(n||0).toLocaleString('es-PA',{minimumFractionDigits:2,maximumFractionDigits:2});
const toast=m=>typeof window.toast==='function'?window.toast(m):console.log(m);
function dt(v){const d=v?new Date(v):null;return d&&!Number.isNaN(d.getTime())?d:null}
function longDate(v){const d=dt(v);return d?d.toLocaleString('es-PA',{day:'2-digit',month:'2-digit',year:'numeric',hour:'numeric',minute:'2-digit'}):'Sin fecha'}
function shortDate(v){const d=dt(v);return d?d.toLocaleDateString('es-PA',{day:'2-digit',month:'short'}).replace('.','').toUpperCase():'—'}
function nameOf(r){return (r.name||r.object||r.code||'Licitación').slice(0,110)}
function safeName(v){return String(v||'pliego.pdf').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-zA-Z0-9._-]+/g,'_')}
function inject(){
 if(!$('#pliegoStyles')){const s=document.createElement('style');s.id='pliegoStyles';s.textContent=`
 .pliego-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px;margin-top:16px}.pliego-card{background:#fff;border:1px solid var(--border);border-radius:18px;padding:18px;box-shadow:var(--shadow)}.pliego-card h3{margin:4px 0 5px;color:var(--navy);font-size:17px}.pliego-card .pc-entity{color:var(--muted);font-size:10px}.pliego-card .pc-object{color:#475467;font-size:11px;line-height:1.55;margin:12px 0}.pc-metrics{display:grid;grid-template-columns:repeat(4,1fr);gap:8px}.pc-metric{background:#f8fafc;border:1px solid #edf1f5;border-radius:10px;padding:9px}.pc-metric span{display:block;color:var(--muted);font-size:8px}.pc-metric b{display:block;color:var(--navy);font-size:11px;margin-top:3px}.pc-foot{display:flex;justify-content:space-between;gap:8px;align-items:center;margin-top:14px}.pliego-detail-head{display:flex;justify-content:space-between;gap:16px;align-items:flex-start}.pliego-detail-head h2{margin:4px 0;color:var(--navy)}.pliego-summary-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin-top:15px}.pliego-summary-grid>div{background:#fff;border:1px solid var(--border);border-radius:12px;padding:12px}.pliego-summary-grid span{display:block;font-size:8px;color:var(--muted)}.pliego-summary-grid b{display:block;margin-top:4px;color:var(--navy);font-size:12px}.pliego-section{background:#fff;border:1px solid var(--border);border-radius:16px;padding:16px;margin-top:14px}.pliego-section h3{margin:0;color:var(--navy)}.req-real{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:12px;padding:12px 0;border-bottom:1px solid #eef2f6}.req-real:last-child{border-bottom:0}.req-real strong{display:block;color:#17365d;font-size:11px;line-height:1.45}.req-real .meta{font-size:9px;color:var(--muted);margin-top:4px}.req-tags{display:flex;gap:5px;flex-wrap:wrap;justify-content:flex-end;align-content:flex-start}.pdf-real{display:flex;align-items:center;justify-content:space-between;gap:10px;border:1px solid #d9e4f0;background:#f8fbff;padding:12px;border-radius:12px;margin-top:9px}.pdf-real strong{color:var(--navy);font-size:11px}.pdf-real span{display:block;color:var(--muted);font-size:9px;margin-top:3px}.pliego-empty{padding:30px;text-align:center;color:var(--muted)}.pliego-empty strong{display:block;color:var(--navy);font-size:14px;margin-bottom:6px}@media(max-width:900px){.pliego-grid{grid-template-columns:1fr}.pc-metrics,.pliego-summary-grid{grid-template-columns:1fr 1fr}.req-real{grid-template-columns:1fr}.req-tags{justify-content:flex-start}}
 `;document.head.appendChild(s)}
 const menu=$('.menu');
 if(menu&&!$('[data-page="pliegos"]')){const b=document.createElement('button');b.className='nav';b.dataset.page='pliegos';b.innerHTML='<span class="ico">▧</span>Pliegos de Licitación';const lic=$('[data-page="licitaciones"]',menu);lic?.insertAdjacentElement('afterend',b)}
 const content=$('.content');
 if(content&&!$('#pliegos')){const sec=document.createElement('section');sec.className='page';sec.id='pliegos';sec.innerHTML='<div id="pliegoView"><div class="hero"><div><h2>Pliegos de Licitación</h2><p>Consulta cada proceso real, su PDF original y el desglose de requisitos detectados.</p></div></div><div class="pliego-empty"><strong>Cargando pliegos…</strong></div></div>';content.appendChild(sec)}
 const page=$('#pliegos');
 if(page){new MutationObserver(()=>{if(page.classList.contains('active')){const t=$('#pageTitle');if(t)t.textContent='Pliegos de Licitación';renderPliegos()}}).observe(page,{attributes:true,attributeFilter:['class']})}
}
async function readyDb(){for(let i=0;i<20;i++){const d=window.__gupsLicitacionesDb;if(d){const {data}=await d.auth.getSession();if(data?.session){DB=d;SESSION=data.session;return true}}await new Promise(r=>setTimeout(r,250))}return false}
async function loadAll(){if(!DB)return;const [a,b,c]=await Promise.all([DB.from('licitaciones').select('*').order('deadline',{ascending:true}),DB.from('licitacion_requirements').select('*').order('created_at',{ascending:true}),DB.from('licitacion_files').select('*').order('uploaded_at',{ascending:false})]);if(a.error)throw a.error;if(b.error)throw b.error;if(c.error)throw c.error;TENDERS=a.data||[];REQS=b.data||[];FILES=c.data||[]}
function analysis(){try{return JSON.parse(localStorage.getItem('gups_licit_shared')||'{}')?.lastAnalysis||null}catch{return null}}
function fields(){const fs=$$('#nueva .field');const by=t=>fs.find(f=>($('label',f)?.textContent||'').toLowerCase().includes(t))?.querySelector('input,textarea,select');return{code:$('#newCode'),entity:$('#newEntity'),object:$('#newObject'),amount:by('monto de referencia'),deadline:by('fecha límite')}}
async function saveRequirements(tender){const a=analysis();if(!a?.requirements?.length)return 0;await DB.from('licitacion_requirements').delete().eq('licitacion_id',tender.id);const payload=a.requirements.map(r=>({licitacion_id:tender.id,name:String(r.name||'Requisito').slice(0,500),source_page:String(r.page||''),source_excerpt:String(r.raw||'').slice(0,1200),subsanability:r.critical?'No subsanable':'Confirmar',critical:!!r.critical,requires_signature:!!r.sign,signer:r.sign?'Por definir':null,required_format:r.format||'PDF',preparation_mode:r.sign?'Firma + escaneo':'Digital directo',stage:0,status:'Pendiente',responsible:null,final_review:false,updated_at:new Date().toISOString()}));const {error}=await DB.from('licitacion_requirements').insert(payload);if(error)throw error;return payload.length}
async function uploadPdf(tender,file){if(!file)return null;const path=`${tender.id}/pliegos/${Date.now()}_${safeName(file.name)}`;const {error}=await DB.storage.from(BUCKET).upload(path,file,{contentType:'application/pdf',upsert:false});if(error)throw error;const {error:fe}=await DB.from('licitacion_files').insert({licitacion_id:tender.id,file_name:file.name,storage_path:path,file_format:'PDF',is_final:true,uploaded_by:SESSION.user.id});if(fe){await DB.storage.from(BUCKET).remove([path]);throw fe}return path}
async function enhancedSave(){if(!DB||!SESSION)return toast('Conecta primero la base de Licitaciones');const f=fields(),code=f.code?.value.trim(),entity=f.entity?.value.trim(),object=f.object?.value.trim(),deadline=f.deadline?.value||'',raw=f.amount?.value.trim()||'',file=$('#pdfInput')?.files?.[0];if(!code)return toast('Completa el número del proceso');if(!entity)return toast('Completa la entidad');if(!object)return toast('Completa el objeto');if(!deadline)return toast('Completa la fecha límite');const amount=raw?Number(raw.replace(/[^0-9.-]/g,'')):null;const when=new Date(deadline);if(raw&&!Number.isFinite(amount))return toast('Revisa el monto');if(Number.isNaN(when.getTime()))return toast('Revisa la fecha límite');const b=$('#saveTender');b.disabled=true;b.textContent='Guardando…';try{const {data,error}=await DB.from('licitaciones').upsert({code,name:object.slice(0,110),entity,object,reference_amount:amount,deadline:when.toISOString(),status:'En preparación',progress:0,created_by:SESSION.user.id,updated_at:new Date().toISOString()},{onConflict:'code'}).select().single();if(error)throw error;let reqCount=0;if(analysis()?.requirements?.length){b.textContent='Guardando desglose…';reqCount=await saveRequirements(data)}if(file){b.textContent='Subiendo pliego PDF…';await uploadPdf(data,file)}await DB.from('licitacion_activity').insert({licitacion_id:data.id,action:'Expediente actualizado',detail:`${code} · ${reqCount} requisitos${file?' · pliego PDF guardado':''}`,actor_id:SESSION.user.id,actor_name:SESSION.user.email});await loadAll();window.gupsRenderRealTenders?.();renderPliegos();toast(file?`Licitación, desglose y pliego guardados`:`Licitación y desglose guardados`);window.gupsNavigate?.('pliegos')}catch(e){console.error(e);const msg=String(e?.message||e);if(/row-level security|unauthorized|policy/i.test(msg))toast('Faltan los permisos de Storage en Supabase. Ejecuta el SQL de políticas.');else toast('No se pudo guardar: '+msg)}finally{b.disabled=false;b.textContent='Guardar licitación'}}
function replaceSave(){const old=$('#saveTender');if(!old||old.dataset.v12==='1')return;const b=old.cloneNode(true);b.dataset.v12='1';old.replaceWith(b);b.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();enhancedSave()})}
function counts(id){const rs=REQS.filter(r=>r.licitacion_id===id),fs=FILES.filter(f=>f.licitacion_id===id);return{all:rs.length,critical:rs.filter(r=>r.critical).length,signs:rs.filter(r=>r.requires_signature).length,files:fs.length}}
function renderPliegos(){const box=$('#pliegoView');if(!box)return;if(!DB){box.innerHTML='<div class="hero"><div><h2>Pliegos de Licitación</h2><p>Conecta la base de Licitaciones para consultar los procesos reales.</p></div></div>';return}if(activePliego){renderDetail(activePliego);return}box.innerHTML=`<div class="hero"><div><h2>Pliegos de Licitación</h2><p>Selecciona una licitación para ver el pliego desglosado, requisitos, firmas, críticos y PDF original.</p></div></div>${TENDERS.length?`<div class="pliego-grid">${TENDERS.map(t=>{const c=counts(t.id);return `<article class="pliego-card"><span class="status ${t.status==='Lista para presentar'?'ok':'warn'}">${esc((t.status||'En preparación').toUpperCase())}</span><h3>${esc(nameOf(t))}</h3><div class="pc-entity">${esc(t.entity||'—')} · ${esc(t.code)}</div><div class="pc-object">${esc(t.object||'')}</div><div class="pc-metrics"><div class="pc-metric"><span>Cierre</span><b>${esc(shortDate(t.deadline))}</b></div><div class="pc-metric"><span>Requisitos</span><b>${c.all}</b></div><div class="pc-metric"><span>No subs.</span><b>${c.critical}</b></div><div class="pc-metric"><span>Firmas</span><b>${c.signs}</b></div></div><div class="pc-foot"><span class="chip">${c.files?c.files+' PDF':'PDF pendiente'}</span><button class="btn small primary" data-open-pliego="${t.id}">Ver pliego →</button></div></article>`}).join('')}</div>`:'<div class="pliego-empty"><strong>No hay licitaciones registradas</strong>Guarda el primer proceso desde Nueva licitación.</div>'}`;$$('[data-open-pliego]',box).forEach(b=>b.onclick=()=>{activePliego=b.dataset.openPliego;renderDetail(activePliego)})}
async function openPdf(path){const {data,error}=await DB.storage.from(BUCKET).createSignedUrl(path,600);if(error)throw error;window.open(data.signedUrl,'_blank','noopener')}
function reqHtml(r){return `<div class="req-real"><div><strong>${esc(r.name)}</strong><div class="meta">Página ${esc(r.source_page||'—')} · ${esc(r.required_format||'PDF')} · Responsable: ${esc(r.responsible||'Por asignar')}</div></div><div class="req-tags"><span class="status ${r.critical?'bad':'blue'}">${esc(r.subsanability||'Confirmar')}</span>${r.requires_signature?'<span class="status warn">Firma</span>':'<span class="chip">Sin firma detectada</span>'}<span class="chip">${esc(r.status||'Pendiente')}</span></div></div>`}
function renderDetail(id){const box=$('#pliegoView'),t=TENDERS.find(x=>x.id===id);if(!box||!t){activePliego=null;renderPliegos();return}const rs=REQS.filter(r=>r.licitacion_id===id),critical=rs.filter(r=>r.critical),signs=rs.filter(r=>r.requires_signature),fs=FILES.filter(f=>f.licitacion_id===id);box.innerHTML=`<div class="pliego-detail-head"><div><button class="btn small" id="backPliegos">← Todos los pliegos</button><h2>${esc(nameOf(t))}</h2><p style="color:var(--muted);margin:0">${esc(t.entity||'—')} · ${esc(t.code)}</p></div><span class="status warn">${esc((t.status||'En preparación').toUpperCase())}</span></div><div class="pliego-summary-grid"><div><span>Fecha límite</span><b>${esc(longDate(t.deadline))}</b></div><div><span>Monto referencia</span><b>${money(t.reference_amount)}</b></div><div><span>Requisitos detectados</span><b>${rs.length}</b></div><div><span>PDF guardados</span><b>${fs.length}</b></div></div><div class="pliego-section"><h3>📑 Pliego original</h3>${fs.length?fs.map((f,i)=>`<div class="pdf-real"><div><strong>${i===0?'Pliego de cargos':'Archivo PDF'} · ${esc(f.file_name)}</strong><span>Subido ${esc(new Date(f.uploaded_at).toLocaleString('es-PA'))}</span></div><button class="btn small primary" data-pdf="${esc(f.storage_path)}">Ver PDF completo</button></div>`).join(''):'<div class="pliego-empty"><strong>PDF pendiente</strong>Vuelve a Nueva licitación, selecciona el PDF y guarda usando el mismo número de proceso.</div>'}</div><div class="pliego-section"><h3>⚠ No subsanables / críticos</h3>${critical.length?critical.map(reqHtml).join(''):'<div class="pliego-empty"><strong>No hay críticos confirmados todavía</strong>Los requisitos no se marcarán como no subsanables si el análisis no encuentra una indicación clara.</div>'}</div><div class="pliego-section"><h3>✍ Firmas requeridas</h3>${signs.length?signs.map(reqHtml).join(''):'<div class="pliego-empty">No se detectaron firmas obligatorias todavía.</div>'}</div><div class="pliego-section"><h3>📋 Todos los requisitos</h3>${rs.length?rs.map(reqHtml).join(''):'<div class="pliego-empty"><strong>Desglose pendiente</strong>Analiza nuevamente el PDF y guarda esta licitación para registrar los requisitos en Supabase.</div>'}</div>`;$('#backPliegos').onclick=()=>{activePliego=null;renderPliegos()};$$('[data-pdf]',box).forEach(b=>b.onclick=async()=>{b.disabled=true;const txt=b.textContent;b.textContent='Abriendo…';try{await openPdf(b.dataset.pdf)}catch(e){toast('No se pudo abrir el PDF: '+(e.message||'error'))}finally{b.disabled=false;b.textContent=txt}})}
function patchExpediente(){const original=window.openTender;if(typeof original!=='function'||original.__v12)return;const wrapped=async function(id){original(id);const t=TENDERS.find(x=>x.id===id);if(!t)return;setTimeout(()=>{const rs=REQS.filter(r=>r.licitacion_id===id),fs=FILES.filter(f=>f.licitacion_id===id);const reqBox=$('#expReqs'),docBox=$('#expDocs'),signBox=$('#expSigns');if(reqBox)reqBox.innerHTML=rs.length?rs.map(reqHtml).join(''):'<div class="note">Analiza y guarda el pliego para generar el desglose.</div>';if(signBox)signBox.innerHTML=rs.filter(r=>r.requires_signature).length?rs.filter(r=>r.requires_signature).map(reqHtml).join(''):'<div class="note">No hay firmas detectadas todavía.</div>';if(docBox)docBox.innerHTML=fs.length?fs.map(f=>`<div class="pdf-real"><div><strong>${esc(f.file_name)}</strong><span>Pliego almacenado en Supabase</span></div><button class="btn small primary" data-exp-pdf="${esc(f.storage_path)}">Ver pliego PDF</button></div>`).join(''):'<div class="note">Este expediente todavía no tiene PDF guardado.</div>';$$('[data-exp-pdf]',docBox||document).forEach(b=>b.onclick=()=>openPdf(b.dataset.expPdf))},60)};wrapped.__v12=true;window.openTender=wrapped}
async function boot(){inject();if(!(await readyDb()))return;await loadAll();replaceSave();patchExpediente();renderPliegos();setInterval(()=>{if(typeof window.openTender==='function'&&!window.openTender.__v12)patchExpediente()},1200)}
inject();if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(boot,1800));else setTimeout(boot,1800);
window.gupsRenderPliegos=()=>{loadAll().then(renderPliegos).catch(console.error)};
})();