create extension if not exists pgcrypto;

create table if not exists public.licitaciones (
  id uuid primary key default gen_random_uuid(),
  code text not null unique,
  name text,
  entity text,
  object text,
  reference_amount numeric,
  deadline timestamptz,
  status text default 'En preparación',
  progress integer default 0,
  created_by uuid references auth.users(id),
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.licitacion_requirements (
  id uuid primary key default gen_random_uuid(),
  licitacion_id uuid references public.licitaciones(id) on delete cascade,
  name text not null,
  source_page text,
  source_excerpt text,
  subsanability text default 'Confirmar',
  critical boolean default false,
  requires_signature boolean default false,
  signer text,
  required_format text default 'PDF',
  preparation_mode text default 'Digital directo',
  stage integer default 0,
  status text default 'Pendiente',
  responsible text,
  final_review boolean default false,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.company_documents (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  category text,
  renewal_rule text,
  issued_at date,
  expires_at date,
  responsible text,
  current_file_path text,
  status text default 'Vigente',
  created_by uuid references auth.users(id),
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.company_document_versions (
  id uuid primary key default gen_random_uuid(),
  document_id uuid references public.company_documents(id) on delete cascade,
  file_path text not null,
  issued_at date,
  expires_at date,
  uploaded_by uuid references auth.users(id),
  uploaded_at timestamptz default now()
);

create table if not exists public.licitacion_files (
  id uuid primary key default gen_random_uuid(),
  licitacion_id uuid references public.licitaciones(id) on delete cascade,
  requirement_id uuid references public.licitacion_requirements(id) on delete set null,
  file_name text not null,
  storage_path text not null,
  file_format text,
  is_final boolean default false,
  uploaded_by uuid references auth.users(id),
  uploaded_at timestamptz default now()
);

create table if not exists public.competitor_offers (
  id uuid primary key default gen_random_uuid(),
  licitacion_id uuid references public.licitaciones(id) on delete cascade,
  company_name text not null,
  amount numeric,
  is_ours boolean default false,
  source text,
  detected_at timestamptz default now()
);

create table if not exists public.opportunity_feedback (
  id uuid primary key default gen_random_uuid(),
  external_key text not null,
  entity text,
  title text,
  decision text,
  tags jsonb default '[]'::jsonb,
  user_id uuid references auth.users(id),
  created_at timestamptz default now()
);

create table if not exists public.licitacion_activity (
  id bigint generated by default as identity primary key,
  licitacion_id uuid references public.licitaciones(id) on delete set null,
  action text not null,
  detail text,
  actor_id uuid references auth.users(id),
  actor_name text,
  created_at timestamptz default now()
);

create table if not exists public.licitacion_notifications (
  id uuid primary key default gen_random_uuid(),
  licitacion_id uuid references public.licitaciones(id) on delete cascade,
  kind text not null,
  title text not null,
  body text,
  due_at timestamptz,
  sent_at timestamptz,
  recipient_role text,
  recipient_user uuid references auth.users(id),
  created_at timestamptz default now()
);

create table if not exists public.licitacion_app_state (
  key text primary key,
  state jsonb not null default '{}'::jsonb,
  updated_by uuid references auth.users(id),
  updated_at timestamptz default now()
);

alter table public.licitaciones enable row level security;
alter table public.licitacion_requirements enable row level security;
alter table public.company_documents enable row level security;
alter table public.company_document_versions enable row level security;
alter table public.licitacion_files enable row level security;
alter table public.competitor_offers enable row level security;
alter table public.opportunity_feedback enable row level security;
alter table public.licitacion_activity enable row level security;
alter table public.licitacion_notifications enable row level security;
alter table public.licitacion_app_state enable row level security;

create policy "read licitaciones" on public.licitaciones for select to authenticated using (true);
create policy "write licitaciones" on public.licitaciones for all to authenticated using (true) with check (true);
create policy "read requirements" on public.licitacion_requirements for select to authenticated using (true);
create policy "write requirements" on public.licitacion_requirements for all to authenticated using (true) with check (true);
create policy "read company docs" on public.company_documents for select to authenticated using (true);
create policy "write company docs" on public.company_documents for all to authenticated using (true) with check (true);
create policy "read versions" on public.company_document_versions for select to authenticated using (true);
create policy "write versions" on public.company_document_versions for all to authenticated using (true) with check (true);
create policy "read files" on public.licitacion_files for select to authenticated using (true);
create policy "write files" on public.licitacion_files for all to authenticated using (true) with check (true);
create policy "read offers" on public.competitor_offers for select to authenticated using (true);
create policy "write offers" on public.competitor_offers for all to authenticated using (true) with check (true);
create policy "read feedback" on public.opportunity_feedback for select to authenticated using (true);
create policy "write feedback" on public.opportunity_feedback for all to authenticated using (true) with check (true);
create policy "read activity" on public.licitacion_activity for select to authenticated using (true);
create policy "write activity" on public.licitacion_activity for all to authenticated using (true) with check (true);
create policy "read notifications" on public.licitacion_notifications for select to authenticated using (true);
create policy "write notifications" on public.licitacion_notifications for all to authenticated using (true) with check (true);
create policy "read app state" on public.licitacion_app_state for select to authenticated using (true);
create policy "write app state" on public.licitacion_app_state for all to authenticated using (true) with check (true);